#!/usr/bin/env node
// Merges validated batches into i18n/locale.<lang>.js.
//
//   node translation/merge.js           # every language with valid output
//   node translation/merge.js es fr
//
// Refuses to merge a language with any failing batch — a half-merged locale is
// harder to reason about than an untranslated one, and the English fallback
// means an untranslated locale is already perfectly usable.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const T = __dirname;
const ROOT = path.join(T, '..');
const OUT = path.join(T, 'out');

const want = process.argv.slice(2);
const files = fs.existsSync(OUT) ? fs.readdirSync(OUT).filter(f => f.endsWith('.json')) : [];
if (!files.length) { console.log('translation/out/ is empty — run run-kimi.sh first'); process.exit(0); }

const byLang = {};
for (const f of files) {
  const m = f.match(/^([a-z]{2,3})\.(ui|content)\.(\d+)\.json$/);
  if (!m) continue;
  const [, lang, kind] = m;
  if (want.length && !want.includes(lang)) continue;
  (byLang[lang] ||= { ui: [], content: [] })[kind].push(f);
}

// Rebuild a nested object from dot-notation keys.
function nest(flat) {
  const out = {};
  for (const [k, v] of Object.entries(flat)) {
    const parts = k.split('.');
    let d = out;
    for (const p of parts.slice(0, -1)) d = (d[p] ||= {});
    d[parts[parts.length - 1]] = v;
  }
  return out;
}

for (const [lang, groups] of Object.entries(byLang)) {
  const all = [...groups.ui, ...groups.content].map(f => path.join(OUT, f));
  try {
    execFileSync('node', [path.join(T, 'validate.js'), ...all], { stdio: 'pipe' });
  } catch (e) {
    console.log(`✗ ${lang}: skipped — some batches fail validation. Run:`);
    console.log(`    node translation/validate.js translation/out/${lang}.*.json`);
    continue;
  }

  const uiFlat = {}, content = {};
  groups.ui.forEach(f => Object.assign(uiFlat, JSON.parse(fs.readFileSync(path.join(OUT, f), 'utf8'))));
  groups.content.forEach(f => Object.assign(content, JSON.parse(fs.readFileSync(path.join(OUT, f), 'utf8'))));

  const localeFile = path.join(ROOT, `i18n/locale.${lang}.js`);

  // Preserve any hand-written epds block: it is an officially validated
  // instrument and never comes from this pipeline.
  let existingEpds = null;
  if (fs.existsSync(localeFile)) {
    global.window = { MYOB_LOCALES: {} };
    delete require.cache[require.resolve(localeFile)];
    try { require(localeFile); existingEpds = (global.window.MYOB_LOCALES[lang] || {}).epds || null; } catch (e) {}
  }

  const obj = {
    // Still false: machine translation, not clinician-reviewed. Set to true by
    // hand only after a clinician has read this language's content.
    reviewed: false,
    translationStatus: 'machine',
    ui: nest(uiFlat),
  };
  if (Object.keys(content).length) obj.content = content;
  if (existingEpds) obj.epds = existingEpds;

  fs.writeFileSync(localeFile,
`// ═══════════════════════════════════════════════════════
// LOCALE: ${lang}
// ═══════════════════════════════════════════════════════
// MACHINE TRANSLATED — generated by translation/run-kimi.sh and merged by
// translation/merge.js. Not yet reviewed by a clinician.
//
// reviewed:false drives the machine-translation notice shown to the patient.
// Do NOT flip it to true until someone qualified has read this content.
//
// Any key omitted here falls back to English at runtime.
//
// ${existingEpds ? 'An epds block is present and was preserved.' : 'No `epds` block: the Edinburgh scale is gated off for this language.'}
// Never machine-translate the EPDS — see TRANSLATING.md.

window.MYOB_LOCALES = window.MYOB_LOCALES || {};

window.MYOB_LOCALES.${lang} = ${JSON.stringify(obj, null, 2)};
`);

  const uiCount = Object.keys(uiFlat).length;
  console.log(`✓ ${lang}: ${uiCount} ui strings, ${Object.keys(content).length} cards -> i18n/locale.${lang}.js`);
}

console.log('\nAfter merging, bump the cache version so users get the update:');
console.log('  sw.js CACHE_NAME, index.html ?v=, i18n/i18n.js ASSET_VERSION');
