// ═══════════════════════════════════════════════════════
// LOCALE: ar
// ═══════════════════════════════════════════════════════
// MACHINE TRANSLATED — generated by translation/run-kimi.sh and merged by
// translation/merge.js. Not yet reviewed by a clinician.
//
// reviewed:false drives the machine-translation notice shown to the patient.
// Do NOT flip it to true until someone qualified has read this content.
//
// Any key omitted here falls back to English at runtime.
//
// No `epds` block: the Edinburgh scale is gated off for this language.
// Never machine-translate the EPDS — see TRANSLATING.md.

window.MYOB_LOCALES = window.MYOB_LOCALES || {};

window.MYOB_LOCALES.ar = {
  "reviewed": false,
  "translationStatus": "machine",
  "ui": {
    "section": {
      "pregnancy": "ما قبل الولادة",
      "labor": "المخاض والولادة",
      "recovery": "التعافي",
      "baby": "حديثو الولادة",
      "faq": "أسئلة شائعة"
    },
    "faq": {
      "badgeMyth": "خرافة",
      "badgeFaq": "سؤال شائع",
      "section5": "القسم 5",
      "faqCommonMyths": "أسئلة شائعة &amp;<br>خرافات شائعة",
      "evidenceBasedAnswersToThe": "إجابات قائمة على الأدلة عن أكثر الأسئلة شيوعاً، بما في ذلك ما سمعتِه من الأهل والأصدقاء ومن الإنترنت."
    },
    "search": {
      "noResultsTitle": "لم يتم العثور على نتائج",
      "noResultsHint": "جرّبي كلمات مختلفة — مثل \"إيبيدورال\"، \"العناية بالحبل السري\"، أو \"نزيف\"",
      "resultCount": {
        "zero": "لا توجد نتائج ({count}) لـ “{q}”",
        "one": "نتيجة واحدة ({count}) لـ “{q}”",
        "two": "{count} نتيجتان لـ “{q}”",
        "few": "{count} نتائج لـ “{q}”",
        "many": "{count} نتيجة لـ “{q}”",
        "other": "{count} نتيجة لـ “{q}”"
      }
    },
    "myinfo": {
      "namePlaceholder": "الاسم",
      "phonePlaceholder": "رقم الهاتف",
      "call": "اتصال",
      "text": "رسالة نصية",
      "contact": {
        "familydoc": "طبيب العائلة",
        "ob": "طبيب التوليد / القابلة",
        "peds": "طبيب الأطفال",
        "mfm": "أخصائي MFM (طب الأم والجنين)",
        "lactation": "استشارية الرضاعة",
        "ld": "المستشفى / فرز المخاض والولادة (L&D)",
        "pharmacy": "الصيدلية"
      },
      "detail": {
        "edd": {
          "label": "تاريخ الولادة المتوقع (EDD)",
          "placeholder": "مثال: 15 يوليو 2026"
        },
        "bloodtype": {
          "label": "فصيلة الدم والعامل الريسوسي (Rh)",
          "placeholder": "مثال: O موجب"
        },
        "gbs": {
          "label": "حالة GBS (البكتيريا العقدية المجموعة ب)",
          "placeholder": "إيجابي / سلبي / لم يُجرَ الفحص بعد"
        },
        "allergies": {
          "label": "حساسية الأدوية",
          "placeholder": "مثال: البنسلين"
        },
        "insurance": {
          "label": "التأمين / رقم العضوية",
          "placeholder": "للرجوع السريع في المستشفى"
        }
      },
      "myInformation": "معلوماتي",
      "myCareTeamKeyDetails": "فريق رعايتي &amp;<br>تفاصيل أساسية",
      "savedOnYourPhoneTap": "محفوظة على هاتفك · اضغطي للاتصال أو المراسلة",
      "careTeamContacts": "جهات اتصال فريق الرعاية",
      "myPregnancyDetails": "تفاصيل حملي",
      "questionsForMyDoctor": "أسئلة لطبيبي",
      "saveMyInformation": "حفظ معلوماتي",
      "exportData": "تصدير البيانات"
    },
    "toast": {
      "contactsSaved": "تم حفظ جهات الاتصال على هاتفك",
      "appInstalled": "تم تثبيت التطبيق! افتحيه من شاشتك الرئيسية في أي وقت",
      "dataExported": "تم تصدير البيانات!",
      "appUpdated": "تم تحديث التطبيق — أعيدي التحميل للحصول على أحدث إصدار"
    },
    "tool": {
      "mood": {
        "unavailableTitle": "فحص المزاج غير متوفر بهذه اللغة",
        "unavailableBody": "مقياس إدنبرة لاكتئاب ما بعد الولادة هو استبيان فحص معتمَد. لا تكون نتائجه ذات معنى إلا باستخدام ترجمة معتمدة رسميًا، لذلك لا نقدم نسخة مترجمة آليًا.",
        "availableIn": "متوفر حاليًا بـ: {langs}. يرجى سؤال فريق رعايتك عن نسخة معتمدة بلغتك.",
        "switchToEnglish": "التبديل إلى الإنجليزية",
        "qCounter": "السؤال {n} من {total}",
        "answerAll": "يرجى الإجابة على جميع الأسئلة الـ{total}",
        "interpLow": "قلق منخفض",
        "interpConcern": "يستحق المناقشة مع طبيبك",
        "interpHigh": "يرجى التواصل مع طبيبك",
        "edinburghPostnatalDepressionScale": "مقياس إدنبرة لاكتئاب ما بعد الولادة",
        "inThePast7Days": "في الأيام السبعة الماضية",
        "yourAnswersAreSavedOnly": "إجاباتك محفوظة على هذا الهاتف فقط.",
        "getMyScore": "احصلي على نتيجتي",
        "scoreOutOf30Based": "النتيجة من 30 · مبني على مقياس إدنبرة لاكتئاب ما بعد الولادة",
        "pastCheckIns": "التقييمات السابقة",
        "selfHarmGuidance": "لقد أجبتِ بأن أفكار إيذاء النفس قد راودتك. يرجى التواصل مع طبيبك، أو الاتصال أو إرسال رسالة إلى 988 (خط الأزمات والوقاية من الانتحار)، أو التوجه إلى أقرب قسم طوارئ.",
        "continueWeekly": "واصلي التقييم أسبوعياً. إذا تغيّر مزاجك، ستساعدك هذه الأداة على متابعته.",
        "talkToDoctor": "التحدث إلى طبيبك — حتى عن نتيجة فحص أولي — خطوة جيدة دائماً. اكتئاب ما بعد الولادة قابل للعلاج بدرجة كبيرة.",
        "instrumentLanguage": "لغة الاستبيان:",
        "change": "تغيير",
        "scoreNote": "النتيجة من {max} · {instrument} · أداة فحص أولي وليست تشخيصاً — ناقشي النتيجة دائماً مع فريق الرعاية",
        "chooseLanguage": "اختاري اللغة التي تودّين الإجابة بها:",
        "validatedOnlyNote": "لا تُقدَّم إلا النسخ المُعتمدة رسمياً من هذا الاستبيان. الترجمة الآلية ستعطي نتيجة أيضاً، لكن تلك النتيجة لن تكون ذات معنى."
      },
      "birthplan": {
        "q": {
          "epidural": {
            "label": "تفضيل تسكين الألم",
            "opt": {
              "epidural": "نعم — إيبيدورال",
              "none": "بدون دواء",
              "open": "إبقاء الخيارات مفتوحة",
              "iv": "دواء وريدي فقط"
            }
          },
          "mobility": {
            "label": "الحركة أثناء المخاض",
            "opt": {
              "walk": "أرغب في المشي/التحرك",
              "bed": "أفضّل البقاء في السرير",
              "wireless": "مراقبة لاسلكية إن توفرت"
            }
          },
          "delayed-cord": {
            "label": "تأخير قطع الحبل السري (30–60 ثانية)",
            "opt": {
              "yes": "نعم من فضلكم",
              "nopref": "لا أفضيلة",
              "discuss": "مناقشته مع الفريق"
            }
          },
          "skin-to-skin": {
            "label": "ملامسة الجلد للجلد فور الولادة",
            "opt": {
              "top": "نعم — أولوية قصوى",
              "ifposs": "نعم إن أمكن",
              "nopref": "لا أفضيلة"
            }
          },
          "pushing": {
            "label": "وضعية الدفع",
            "opt": {
              "nurse": "بتوجيه الممرضة",
              "positions": "أرغب في تجربة وضعيات مختلفة",
              "squat": "القرفصاء / الوقوف"
            }
          },
          "episiotomy": {
            "label": "شق العجان",
            "opt": {
              "avoid": "تجنّبه ما لم يكن ضرورياً",
              "trust": "أثق بتقدير الفريق الطبي",
              "nopref": "لا تفضيل لديّ"
            }
          },
          "cord-cut": {
            "label": "من يقطع الحبل السري",
            "opt": {
              "support": "المرافق",
              "team": "الفريق الطبي",
              "nopref": "لا تفضيل لديّ"
            }
          },
          "photos": {
            "label": "التصوير أثناء الولادة",
            "opt": {
              "yes": "نعم، من فضلكم",
              "none": "لا تصوير أثناء الولادة",
              "after": "التصوير بعد الولادة فقط"
            }
          },
          "visitors": {
            "label": "الزوار أثناء المخاض",
            "opt": {
              "supportonly": "المرافق فقط",
              "family": "أهلاً بالعائلة المقرّبة",
              "none": "بدون زوار"
            }
          },
          "breastfeed": {
            "label": "خطة الرضاعة",
            "opt": {
              "exclusive": "رضاعة طبيعية حصرية",
              "supplement": "رضاعة طبيعية + حليب صناعي",
              "formula": "حليب صناعي فقط",
              "unsure": "لم أقرر بعد"
            }
          },
          "csection": {
            "label": "إذا لزمت الولادة القيصرية",
            "opt": {
              "lowscreen": "خفض الستارة (لرؤية المولود)",
              "supportor": "وجود المرافق في غرفة العمليات",
              "skinor": "ملامسة الجلد للجلد في غرفة العمليات إن أمكن",
              "standard": "الإجراءات المعتادة مناسبة"
            }
          },
          "music": {
            "label": "الأجواء",
            "opt": {
              "playlist": "موسيقى / قائمة التشغيل الخاصة بي",
              "quiet": "أجواء هادئة",
              "nopref": "لا تفضيل لديّ"
            }
          }
        },
        "additionalNotesComments": "ملاحظات / تعليقات إضافية",
        "copyToShare": "نسخ للمشاركة",
        "printPdf": "طباعة / PDF",
        "additionalNotes": "ملاحظات إضافية:",
        "myBirthPreferences": "تفضيلاتي للولادة",
        "pregnancyBirthGuideEvidenceBased": "دليل الحمل والولادة · قائم على الأدلة · خاص ويعمل دون اتصال",
        "anyOtherPreferencesConcernsOr": "أي تفضيلات أو مخاوف أو معلومات أخرى للفريق الطبي…",
        "copiedToClipboard": "تم النسخ إلى الحافظة!",
        "copyNotSupportedOnThis": "النسخ غير مدعوم في هذا المتصفح",
        "selectPreferences": "اختاري تفضيلاتك أدناه. سيظهر الملخص في الأسفل ويمكنك مشاركته مع فريق الرعاية."
      },
      "kick": {
        "startSession": "بدء الجلسة",
        "movementsThisSession": "حركة في هذه الجلسة",
        "elapsed": "الوقت المنقضي:",
        "20000Limit": "الحد 2:00:00",
        "lessThan10MovementsIn": "⚠ أقل من 10 حركات خلال ساعتين",
        "thisMayNeedAttentionCall": "قد يحتاج هذا إلى انتباه — اتصلي بطبيبك.",
        "10MovementsReached": "تم الوصول إلى 10 حركات!",
        "startAnotherSession": "بدء جلسة أخرى",
        "sessionHistory": "سجل الجلسات",
        "noSessions": "لا توجد جلسات بعد",
        "countMovements": "عدّي حركات الجنين خلال جلسة نشطة.",
        "goal": "الهدف: 10 حركات خلال ساعتين",
        "tapForEach": "👶 اضغطي عند كل حركة",
        "endEarly": "إنهاء الجلسة مبكراً",
        "pass": "تحقق",
        "low": "منخفض"
      },
      "common": {
        "recentContractions": "الانقباضات الأخيرة",
        "timeToGoToThe": "🚨 حان وقت الذهاب إلى المستشفى",
        "511PatternReached": "تم بلوغ نمط 5-1-1"
      },
      "feed": {
        "feedsInLast24Hrs": "الرضعات خلال آخر 24 ساعة",
        "lastFeed": "آخر رضعة",
        "logAFeeding": "+ تسجيل رضعة",
        "feedLog": "سجل الرضاعة",
        "feedLogged": "تم تسجيل الرضعة",
        "noFeeds": "لم تُسجَّل أي رضعات بعد.",
        "fewFeedsTitle": "⚠ أقل من 8 رضعات اليوم",
        "fewFeedsBody": "يحتاج المواليد عادةً إلى 8–12 رضعة كل 24 ساعة. إذا كان من الصعب إيقاظ الطفل أو لم يكن وزنه يزداد، اتصلي بطبيبك.",
        "breast": "🤱 رضاعة طبيعية",
        "bottle": "🍼 زجاجة",
        "minutes": "{n} دقيقة"
      },
      "diaper": {
        "wetToday": "مبلّلة اليوم",
        "dirtyToday": "متسخة اليوم",
        "bothWetDirty": "+ الاثنان معاً (مبلّلة ومتسخة)",
        "whatToExpectByAge": "ما هو المتوقع حسب العمر",
        "day1212": "اليوم 1–2: حفاضان مبلّلان 1–2 · اليوم 3–4: 3–4 مبلّلة · اليوم 5 فما بعد: 6 أو أكثر مبلّلة، و3–4 متسخة يومياً. أقل من 6 حفاضات مبلّلة بعد اليوم الخامس ← اتصلي بطبيبك.",
        "todaySLog": "سجل اليوم",
        "noDiapers": "لم تُسجَّل حفاضات اليوم."
      },
      "jaundice": {
        "babySBirthDate": "تاريخ ميلاد الطفل",
        "set": "حفظ",
        "birthDateSaved": "تم حفظ تاريخ الميلاد",
        "dayOfLife": "يوم من العمر",
        "resolvesByNow": "معظم حالات اليرقان تزول عند هذه المرحلة",
        "callImmediatelyIf": "اتصلي بطبيبك فوراً إذا",
        "setBirthDateHint": "أدخلي تاريخ ميلاد الطفل أعلاه لعرض الإرشاد يوماً بيوم.",
        "day1": "اليوم الأول — يُفحص البيليروبين قبل الخروج من المستشفى. يراقب طاقم التمريض الطفل.",
        "day2": "مستويات البيليروبين في ارتفاع. يجري المستشفى فحوصاً قبل الخروج. راقبي اصفرار الجلد وبياض العينين.",
        "day3": "يبلغ اليرقان ذروته بين اليوم الثالث والخامس عند معظم الأطفال. قد يصبح اللون الأصفر أوضح. الرضاعة المتكررة (8–12 مرة يومياً) تساعد الجسم على التخلص من البيليروبين.",
        "day4": "فترة ذروة اليرقان. تأكدي من أن الطفل يرضع جيداً وأن الحفاضات مبلّلة. غالباً ما تُحدَّد زيارة طبيب الأطفال في هذا الوقت.",
        "day5": "زيارة طبيب الأطفال: فحص الوزن ومستوى البيليروبين. يُفترض أن تبدأ المستويات بالاستقرار. إذا كان الطفل خاملاً ولا يرضع، اتصلي بطبيبك.",
        "day6": "يُفترض أن تبدأ المستويات بالانخفاض عند الأطفال المولودين في موعدهم. واصلي الرضاعة المتكررة. إذا كان الجلد شديد الاصفرار أو لم يستيقظ الطفل للرضاعة، اتصلي بطبيبك.",
        "day7": "يتحسّن اليرقان عند معظم الأطفال المولودين في موعدهم في هذه المرحلة. راقبي امتداد الاصفرار إلى الساقين والقدمين، فذلك يدل على مستويات أعلى.",
        "day10": "عند معظم الأطفال المولودين في موعدهم يكون اليرقان قد زال تقريباً. إذا استمر أو ازداد، سيرغب طبيبك في فحص مستوى البيليروبين.",
        "day14": "زيارة الأسبوعين. يُفترض أن يكون اليرقان قد زال عند الأطفال المولودين في موعدهم. اليرقان المستمر بعد أسبوعين قد يحتاج إلى تقييم إضافي — أخبري طبيبك.",
        "day21": "اليرقان الذي يستمر أكثر من ثلاثة أسابيع يُعد مطوّلاً ويجب تقييمه. قد يستمر اليرقان الخفيف لفترة أطول عند الأطفال الذين يرضعون طبيعياً، لكنه يحتاج إلى فحص رغم ذلك.",
        "dayWatch": "اليوم {day} — ما ينبغي مراقبته",
        "redFlags": "الطفل لا يستيقظ للرضاعة · اصفرار شديد يمتد إلى الساقين · تقوّس الظهر أو بكاء حاد النبرة · براز أبيض أو رمادي · بول داكن جداً"
      },
      "bp": {
        "logBloodPressure": "+ تسجيل ضغط الدم",
        "whenToCallYourDoctor": "متى تتصلين بطبيبك",
        "anyReading14090During": "أي قراءة ≥ 140/90 أثناء الحمل أو بعد الولادة. القراءة ≥ 160/110 حالة طارئة — اتصلي بقسم الولادة (L&D) أو 911.",
        "readings": "القراءات",
        "enterValidNumbersEG": "أدخلي أرقاماً صحيحة (مثلاً 118 / 76)",
        "highReadingContactYourDoctor": "قراءة مرتفعة — تواصلي مع طبيبك",
        "noReadings": "لم تُسجَّل أي قراءات بعد.",
        "highOnRecord": "⚠ قراءة مرتفعة مسجّلة",
        "cat": {
          "severe": "مرتفع جداً",
          "high": "مرتفع",
          "elevated": "مرتفع قليلاً",
          "normal": "طبيعي"
        },
        "recentSummary": "قراءتك الأخيرة ({reading}) تقع ضمن نطاق {cat}. تواصلي مع طبيبك اليوم."
      },
      "weight": {
        "yourProfile": "ملفك الشخصي",
        "prePregnancyWeightLbs": "الوزن قبل الحمل (lbs)",
        "prePregnancyBmi": "مؤشر كتلة الجسم (BMI) قبل الحمل",
        "saveProfile": "حفظ الملف",
        "logWeight": "+ تسجيل الوزن",
        "weightLog": "سجل الوزن",
        "profileSaved": "تم حفظ الملف",
        "enterValidWeightAndPregnancy": "أدخلي وزناً وأسبوع حمل صحيحين",
        "noWeights": "لم يُسجَّل أي وزن بعد.",
        "recommendedGain": "الزيادة الإجمالية الموصى بها:",
        "forFullPregnancy": "خلال فترة الحمل كاملة.",
        "setYourProfile": "أعدّي ملفك الشخصي",
        "setProfileHint": "أدخلي مؤشر كتلة الجسم (BMI) قبل الحمل لعرض إرشادات IOM لزيادة الوزن الخاصة بك.",
        "bmi": {
          "under": "نقص الوزن",
          "normal": "وزن طبيعي",
          "over": "زيادة الوزن",
          "obese": "سمنة"
        },
        "iomFor": "إرشاد IOM الخاص بك ({range})"
      },
      "appts": {
        "addVisit": "+ إضافة زيارة",
        "questionsToAsk": "أسئلة لطرحها",
        "noneAdded": "لم تُضف أي أسئلة",
        "notesFromVisit": "ملاحظات من الزيارة",
        "edit": "تعديل",
        "delete": "حذف",
        "visitDeleted": "تم حذف الزيارة",
        "noVisits": "لا توجد زيارات مسجّلة بعد. أضيفي واحدة أعلاه لتتبّع أسئلتك وملاحظاتك.",
        "deleteConfirm": "هل تريدين حذف هذه الزيارة؟"
      },
      "cx": {
        "noContractions": "لم تُسجَّل أي انقباضات بعد.<br>اضغطي «بدء الانقباضة» عند بدء انقباضة.",
        "noContraction": "لا توجد انقباضة حالياً",
        "inProgress": "انقباضة جارية…",
        "startBtn": "بدء الانقباضة",
        "endBtn": "انتهاء الانقباضة",
        "clearAll": "مسح الكل",
        "clearConfirm": "هل تريدين مسح كل سجلات الانقباضات؟",
        "duration": "مدتها {d}",
        "interval": "كل {t}"
      },
      "i18n": {
        "intro": "قارني كل عبارة في هذا التطبيق بالنص الإنجليزي الأصلي. إذا بدت صياغة ما غير صحيحة، اكتبي نسخة أفضل. تبقى اقتراحاتك على هذا الهاتف حتى تصدّريها.",
        "searchPlaceholder": "ابحثي في العبارات…",
        "needsWork": "تحتاج مراجعة",
        "all": "الكل",
        "suggested": "مقترحة",
        "suggestPlaceholder": "اقترحي صياغة أفضل…",
        "nothingToShow": "لا يوجد ما يُعرض بهذه الفلاتر.",
        "showingFirst": "عرض أول {n} من {total}. استخدمي البحث لتضييق النتائج.",
        "export": "تصدير اقتراحاتي",
        "clear": "مسح",
        "clearConfirm": "هل تريدين حذف كل اقتراحاتك لهذه اللغة؟",
        "nothingToExport": "لا توجد اقتراحات للتصدير بعد",
        "exported": "تم تصدير {n} اقتراحاً",
        "submit": "إرسال",
        "sending": "جارٍ الإرسال…",
        "sent": "تم الإرسال — شكراً لك",
        "sentShort": "تم الإرسال ✓",
        "typeFirst": "اكتبي اقتراحاً أولاً",
        "sendFailed": "تعذّر الإرسال — تم الحفظ هنا، استخدمي التصدير",
        "rateLimited": "عدد كبير من الإرسالات، حاولي لاحقاً",
        "offlineSaved": "دون اتصال — تم الحفظ هنا، استخدمي التصدير",
        "privacy": "لا يُرسل سوى العبارة واقتراحك. لا يغادر أي شيء من سجلاتك هذا الهاتف."
      }
    },
    "theme": {
      "toggle": "تبديل الوضع الداكن"
    },
    "lang": {
      "label": "اللغة",
      "change": "تغيير اللغة",
      "unreviewedNotice": "هذه الترجمة آلية ولم يراجعها بعد مختص طبي. للقرارات الطبية، يرجى التأكد من فريق الرعاية أو التبديل إلى الإنجليزية.",
      "loadFailed": "تعذّر التحميل",
      "inProgress": "الترجمة قيد التنفيذ"
    },
    "app": {
      "title": "دليل الحمل",
      "tagline": "",
      "description": "دليل قائم على الأدلة للحمل والمخاض والولادة وما بعد الولادة. يعمل دون اتصال.",
      "home": "الرئيسية",
      "prenatal": "قبل الولادة",
      "labor": "المخاض",
      "recovery": "التعافي",
      "baby": "الطفل",
      "faq": "أسئلة شائعة",
      "tools": "الأدوات",
      "offlineBanner": "⚠ أنتِ غير متصلة — كل المحتوى ما زال متاحاً",
      "searchPlaceholder": "ابحثي في كل المواضيع…"
    },
    "home": {
      "myInfoContacts": "معلوماتي<br>وجهات الاتصال",
      "saveYourCareTeamContacts": "احفظي جهات اتصال فريق الرعاية",
      "tapToCallOrText": "اضغطي للاتصال أو إرسال رسالة مباشرة من التطبيق",
      "callYourDoctorIf": "اتصلي بطبيبك إذا…",
      "duringPregnancy": "أثناء الحمل",
      "vaginalBleeding": "نزيف مهبلي",
      "fluidGushingOrTrickling": "تدفق أو تسرب سائل",
      "babyNotMovingNormally": "حركة الجنين غير طبيعية",
      "severeHeadache": "صداع شديد",
      "visionChanges": "تغيّرات في الرؤية",
      "suddenSwellingOfFaceHands": "تورم مفاجئ في الوجه أو اليدين",
      "fever1004F": "حمّى &gt;100.4°F",
      "contractionsBefore37Weeks": "انقباضات قبل الأسبوع 37",
      "afterDelivery": "بعد الولادة",
      "soaking1PadHr2": "تشبّع أكثر من فوطة واحدة في الساعة × ساعتين",
      "woundOpensOrOozes": "انفتاح الجرح أو نزّه",
      "legRednessSwelling": "احمرار أو تورم في الساق",
      "chestPainOrTroubleBreathing": "ألم في الصدر أو صعوبة في التنفس",
      "thoughtsOfSelfHarm": "أفكار بإيذاء النفس",
      "heroTitle": "اعرفي ما الذي<br>ينتظرك. واسألي<br>الأسئلة الصحيحة.",
      "heroDesc": "من أول زيارة قبل الولادة وحتى الولادة والتعافي، يجمع Obiana كل شيء في مكان واحد."
    },
    "pregnancy": {
      "section1": "القسم 1",
      "prenatalVisitsPregnancy": "زيارات ما قبل الولادة<br>والحمل",
      "aVisitByVisitGuide": "دليل زيارة بزيارة، وشرح فحوصات عنق الرحم، والرياضة أثناء الحمل، وما الذي تسألين عنه في كل مرحلة."
    },
    "labor": {
      "section2": "القسم 2",
      "laborDelivery": "المخاض<br>والولادة",
      "signsOfLaborWhatHappens": "علامات المخاض، وما يحدث عند وصولك، وخيارات تسكين الألم، والولادة القيصرية، ورعاية الحمل عالي الخطورة."
    },
    "recovery": {
      "section3": "القسم 3",
      "postpartumRecovery": "التعافي<br>بعد الولادة",
      "physicalHealingMoodAndPpd": "الشفاء الجسدي، والحالة المزاجية واكتئاب ما بعد الولادة، والراحة الحوضية، والعودة إلى الرياضة، ومتى تعودين إلى المنزل."
    },
    "baby": {
      "section4": "القسم 4",
      "yourNewborn": "مولودك<br>الجديد",
      "breastfeedingFormulaCordCareSafe": "الرضاعة الطبيعية، والحليب الصناعي، والعناية بالحبل السري، والنوم الآمن، وشكل المولود الطبيعي، ومواعيد المتابعة."
    },
    "tools": {
      "dailyTools": "أدوات يومية",
      "trackersPlanners": "أدوات التتبّع<br>والتخطيط",
      "timeContractionsCountKicksLog": "قياس زمن الانقباضات، وعدّ الركلات، وتسجيل الرضاعة والحفاضات، ومتابعة ضغط الدم، والتخطيط لولادتك، والمزيد.",
      "labor": "المخاض",
      "kickCounter": "عدّاد الركلات",
      "10MovesIn2Hours": "10 حركات خلال ساعتين — تسجيل الجلسات والسجل",
      "contractionTimer": "مؤقّت الانقباضات",
      "tapStartStop51": "اضغطي بدء/إيقاف · تنبيه 5-1-1 · متى تذهبين",
      "newbornPostpartum": "المولود وما بعد الولادة",
      "feedingLog": "سجل الرضاعة",
      "breastOrBottle24Hr": "ثدي أو زجاجة · عدّ 24 ساعة · تنبيه عند الانخفاض",
      "diaperLog": "سجل الحفاضات",
      "wetDirtyCountDailyTotals": "عدّ المبلّلة والمتسخة · مجاميع يومية للطبيب",
      "jaundiceTracker": "متتبّع اليرقان",
      "dayByDayGuidanceFrom": "إرشاد يوماً بيوم منذ الولادة",
      "moodCheckIn": "تقييم المزاج",
      "epdsScreenWeeklyTrackingFlags": "فحص EPDS · متابعة أسبوعية · تنبيه عند القلق",
      "pregnancyMonitoring": "متابعة الحمل",
      "bloodPressure": "ضغط الدم",
      "logReadingsFlags14090": "تسجيل القراءات · تنبيه تلقائي عند ≥ 140/90",
      "weightTracker": "متتبّع الوزن",
      "logByWeekIomGain": "تسجيل حسب الأسبوع · إرشادات IOM لزيادة الوزن حسب مؤشر كتلة الجسم (BMI)",
      "planning": "التخطيط",
      "birthPlanBuilder": "منشئ خطة الولادة",
      "guidedChoicesShareableOnePage": "خيارات موجّهة · ملخص من صفحة واحدة قابل للمشاركة",
      "visitNotes": "ملاحظات الزيارات",
      "questionsBeforeNotesDuringEvery": "أسئلة قبل الزيارة · ملاحظات في كل زيارة",
      "translationHelper": "مساعد الترجمة",
      "reviewSuggestWording": "مراجعة الصياغة · اقتراح ترجمة أفضل"
    },
    "toolkick": {
      "kickCounter": "عدّاد الركلات"
    },
    "toolcontractions": {
      "contractionTimer": "مؤقّت الانقباضات"
    },
    "toolfeeding": {
      "feedingLog": "سجل الرضاعة"
    },
    "tooldiapers": {
      "diaperLog": "سجل الحفاضات"
    },
    "tooljaundice": {
      "jaundiceTracker": "متتبّع اليرقان"
    },
    "toolbp": {
      "bloodPressureLog": "سجل ضغط الدم"
    },
    "toolweight": {
      "weightTracker": "متتبّع الوزن"
    },
    "toolmood": {
      "moodCheckIn": "تقييم المزاج"
    },
    "toolbirthplan": {
      "birthPlanBuilder": "منشئ خطة الولادة"
    },
    "toolappts": {
      "visitNotes": "ملاحظات الزيارات"
    },
    "modalFeed": {
      "logAFeeding": "تسجيل رضعة",
      "type": "النوع",
      "breast": "🤱 ثدي",
      "bottle": "🍼 زجاجة",
      "side": "الجهة",
      "left": "اليسرى",
      "right": "اليمنى",
      "both": "كلتاهما",
      "durationMinutes": "المدة (دقائق)",
      "amountOz": "الكمية (oz)",
      "saveFeed": "حفظ الرضعة"
    },
    "modalBp": {
      "logBloodPressure": "تسجيل ضغط الدم",
      "systolicTop": "الانقباضي (الرقم العلوي)",
      "diastolicBottom": "الانبساطي (الرقم السفلي)",
      "normalRange": "المعدل الطبيعي",
      "below12080IsNormal": "أقل من 120/80 طبيعي. القراءة ≥ 140/90 أثناء الحمل تحتاج إلى متابعة في نفس اليوم.",
      "saveReading": "حفظ القراءة"
    },
    "modalWeight": {
      "logWeight": "تسجيل الوزن",
      "weightLbs": "الوزن (lbs)",
      "weekOfPregnancy": "أسبوع الحمل",
      "save": "حفظ"
    },
    "modalAppt": {
      "addVisit": "إضافة زيارة",
      "visitType": "نوع الزيارة",
      "date": "التاريخ",
      "questionsToAskBeforehand": "أسئلة تطرحينها قبل الزيارة",
      "notesFromVisit": "ملاحظات من الزيارة",
      "saveVisit": "حفظ الزيارة"
    },
    "apptType": {
      "selectType": "اختاري النوع…",
      "obRoutine": "نساء وولادة – زيارة روتينية",
      "obTriage": "نساء وولادة – فرز قسم الولادة (L&amp;D) / زيارة غير مجدولة",
      "mfmConsult": "استشارة طب الأم والجنين (MFM)",
      "mfmFollowup": "متابعة طب الأم والجنين (MFM)",
      "endo": "الغدد الصماء",
      "cardio": "القلب",
      "nephro": "الكلى",
      "ultrasound": "تصوير بالموجات فوق الصوتية",
      "nst": "اختبار عدم الإجهاد (NST)",
      "lactation": "استشارة الرضاعة",
      "pp2wk": "ما بعد الولادة – أسبوعان",
      "pp6wk": "ما بعد الولادة – 6 أسابيع",
      "peds25d": "طب الأطفال – 2–5 أيام",
      "peds2wk": "طب الأطفال – أسبوعان",
      "peds2mo": "طب الأطفال – شهران",
      "family": "طبيب الأسرة",
      "other": "أخرى"
    },
    "install": {
      "addToPhone": "أضيفيه إلى هاتفك"
    },
    "common": {
      "toolsBack": "الأدوات"
    },
    "nav": {
      "prenatal": "زيارات<br>ما قبل الولادة",
      "labor": "المخاض<br>والولادة",
      "recovery": "التعافي<br>بعد الولادة",
      "baby": "مولودك<br>الجديد",
      "toolsTrackers": "الأدوات<br>والمتتبّعات"
    },
    "tooli18n": {
      "translationHelper": "مساعد الترجمة"
    }
  }
};
