// ═══════════════════════════════════════════════════════
// LOCALE: zh
// ═══════════════════════════════════════════════════════
// MACHINE TRANSLATED — generated by translation/run-kimi.sh and merged by
// translation/merge.js. Not yet reviewed by a clinician.
//
// reviewed:false drives the machine-translation notice shown to the patient.
// Do NOT flip it to true until someone qualified has read this content.
//
// Any key omitted here falls back to English at runtime.
//
// No `epds` block: the Edinburgh scale is gated off for this language.
// Never machine-translate the EPDS — see TRANSLATING.md.

window.MYOB_LOCALES = window.MYOB_LOCALES || {};

window.MYOB_LOCALES.zh = {
  "reviewed": false,
  "translationStatus": "machine",
  "ui": {
    "section": {
      "pregnancy": "产前检查",
      "labor": "分娩",
      "recovery": "产后恢复",
      "baby": "新生儿",
      "faq": "常见问题"
    },
    "faq": {
      "badgeMyth": "误区",
      "badgeFaq": "问答",
      "section5": "第 5 部分",
      "faqCommonMyths": "常见问题<br>与误区",
      "evidenceBasedAnswersToThe": "针对最常见问题的循证解答，也包括你从家人、朋友和网上听来的说法。"
    },
    "search": {
      "noResultsTitle": "没有找到结果",
      "noResultsHint": "试试其他关键词，例如「无痛分娩」「脐带护理」或「出血」",
      "resultCount": {
        "other": "找到 {count} 条关于「{q}」的结果"
      }
    },
    "myinfo": {
      "namePlaceholder": "姓名",
      "phonePlaceholder": "电话号码",
      "call": "拨打",
      "text": "发短信",
      "contact": {
        "familydoc": "家庭医生",
        "ob": "产科医生 / 助产士",
        "peds": "儿科医生",
        "mfm": "母胎医学（MFM）专科医生",
        "lactation": "哺乳顾问",
        "ld": "医院 / 产房分诊（L&D）",
        "pharmacy": "药房"
      },
      "detail": {
        "edd": {
          "label": "预产期（EDD）",
          "placeholder": "例如 2026 年 7 月 15 日"
        },
        "bloodtype": {
          "label": "血型与 Rh 因子",
          "placeholder": "例如 O 型阳性"
        },
        "gbs": {
          "label": "GBS（B 族链球菌）检查结果",
          "placeholder": "阳性 / 阴性 / 尚未检查"
        },
        "allergies": {
          "label": "药物过敏史",
          "placeholder": "例如 青霉素"
        },
        "insurance": {
          "label": "保险 / 会员号",
          "placeholder": "方便在医院快速查看"
        }
      },
      "myInformation": "我的信息",
      "myCareTeamKeyDetails": "我的医疗团队<br>与重要信息",
      "savedOnYourPhoneTap": "已保存在你的手机上 · 点击即可拨打或发短信",
      "careTeamContacts": "医疗团队联系方式",
      "myPregnancyDetails": "我的怀孕信息",
      "questionsForMyDoctor": "想问医生的问题",
      "saveMyInformation": "保存我的信息",
      "exportData": "导出数据"
    },
    "toast": {
      "contactsSaved": "联系人已保存到你的手机",
      "appInstalled": "应用已安装！随时可从主屏幕打开",
      "dataExported": "数据已导出！",
      "appUpdated": "应用已更新，请重新加载以获取最新版本"
    },
    "tool": {
      "mood": {
        "unavailableTitle": "此语言暂不支持情绪自评",
        "unavailableBody": "爱丁堡产后抑郁量表是一份经过验证的筛查问卷。只有使用官方验证过的译本，评分才具有意义，因此我们不提供机器翻译版本。",
        "availableIn": "目前支持的语言：{langs}。请向你的医疗团队咨询是否有你所用语言的验证版本。",
        "switchToEnglish": "切换到英文",
        "qCounter": "第 {n} 题，共 {total} 题",
        "answerAll": "请回答全部 {total} 道题",
        "interpLow": "风险较低",
        "interpConcern": "建议与医生讨论",
        "interpHigh": "请联系你的医生",
        "edinburghPostnatalDepressionScale": "爱丁堡产后抑郁量表",
        "inThePast7Days": "过去 7 天内",
        "yourAnswersAreSavedOnly": "你的答案只保存在这部手机上。",
        "getMyScore": "查看我的得分",
        "scoreOutOf30Based": "满分 30 分 · 依据爱丁堡产后抑郁量表",
        "pastCheckIns": "过往记录",
        "selfHarmGuidance": "你表示曾有过伤害自己的想法。请联系你的医生，拨打或发短信至 988（自杀与危机生命线），或前往最近的急诊室。",
        "continueWeekly": "请继续每周自评。如果情绪有变化，这个工具可以帮你追踪。",
        "talkToDoctor": "和医生谈一谈，哪怕只是关于一个筛查分数，始终是好的一步。产后抑郁是很可以治疗的。",
        "instrumentLanguage": "问卷语言：",
        "change": "更改",
        "scoreNote": "满分 {max} 分 · {instrument} · 这是筛查工具而非诊断，请务必与你的医疗团队讨论结果",
        "chooseLanguage": "请选择你想用来作答的语言：",
        "validatedOnlyNote": "只提供经过官方验证的问卷版本。机器翻译同样会算出分数，但那个分数没有意义。"
      },
      "birthplan": {
        "q": {
          "epidural": {
            "label": "镇痛方式偏好",
            "opt": {
              "epidural": "要，硬膜外镇痛",
              "none": "不用药物",
              "open": "先不决定，视情况而定",
              "iv": "只用静脉注射药物"
            }
          },
          "mobility": {
            "label": "产程中的活动",
            "opt": {
              "walk": "想走动、变换姿势",
              "bed": "更愿意待在床上",
              "wireless": "如果有，希望用无线胎心监护"
            }
          },
          "delayed-cord": {
            "label": "延迟结扎脐带（30–60 秒）",
            "opt": {
              "yes": "好的，希望这样",
              "nopref": "没有特别偏好",
              "discuss": "想和医疗团队讨论"
            }
          },
          "skin-to-skin": {
            "label": "出生后立即肌肤接触",
            "opt": {
              "top": "要，这是我最看重的",
              "ifposs": "如果可以的话，要",
              "nopref": "没有特别偏好"
            }
          },
          "pushing": {
            "label": "用力时的体位",
            "opt": {
              "nurse": "听护士指导",
              "positions": "想尝试不同体位",
              "squat": "蹲位 / 站位"
            }
          },
          "episiotomy": {
            "label": "会阴侧切",
            "opt": {
              "avoid": "非必要不做",
              "trust": "相信医疗团队的判断",
              "nopref": "没有特别偏好"
            }
          },
          "cord-cut": {
            "label": "由谁剪脐带",
            "opt": {
              "support": "陪产者",
              "team": "医疗团队",
              "nopref": "没有特别偏好"
            }
          },
          "photos": {
            "label": "分娩过程中拍照",
            "opt": {
              "yes": "好的，希望拍",
              "none": "分娩过程中不要拍照",
              "after": "只在分娩后拍照"
            }
          },
          "visitors": {
            "label": "产程中的探视",
            "opt": {
              "supportonly": "只要陪产者",
              "family": "欢迎至亲家属",
              "none": "不要探视"
            }
          },
          "breastfeed": {
            "label": "喂养计划",
            "opt": {
              "exclusive": "纯母乳喂养",
              "supplement": "母乳 + 添加配方奶",
              "formula": "只用配方奶",
              "unsure": "还没想好"
            }
          },
          "csection": {
            "label": "如果需要剖腹产",
            "opt": {
              "lowscreen": "放低挡布（想看到宝宝）",
              "supportor": "陪产者进手术室",
              "skinor": "如果可以，在手术室做肌肤接触",
              "standard": "按常规做法即可"
            }
          },
          "music": {
            "label": "环境氛围",
            "opt": {
              "playlist": "放音乐 / 我自己的歌单",
              "quiet": "安静的环境",
              "nopref": "没有特别偏好"
            }
          }
        },
        "additionalNotesComments": "补充说明 / 备注",
        "copyToShare": "复制以分享",
        "printPdf": "打印 / PDF",
        "additionalNotes": "补充说明：",
        "myBirthPreferences": "我的分娩意愿",
        "pregnancyBirthGuideEvidenceBased": "怀孕与分娩指南 · 循证内容 · 私密且可离线使用",
        "anyOtherPreferencesConcernsOr": "其他想让医疗团队知道的意愿、顾虑或信息……",
        "copiedToClipboard": "已复制到剪贴板！",
        "copyNotSupportedOnThis": "此浏览器不支持复制",
        "selectPreferences": "在下方选择你的意愿。摘要会显示在底部，可以分享给你的医疗团队。",
        "generatedOn": "生成于 {date}"
      },
      "kick": {
        "startSession": "开始记录",
        "movementsThisSession": "次胎动（本次记录）",
        "elapsed": "已用时：",
        "20000Limit": "上限 2:00:00",
        "lessThan10MovementsIn": "⚠ 2 小时内胎动不足 10 次",
        "thisMayNeedAttentionCall": "这可能需要注意，请联系你的医生。",
        "10MovementsReached": "已达到 10 次胎动！",
        "startAnotherSession": "再记录一次",
        "sessionHistory": "记录历史",
        "noSessions": "还没有记录",
        "countMovements": "在一次记录中数一数胎动。",
        "goal": "目标：2 小时内 10 次胎动",
        "tapForEach": "👶 每次胎动点一下",
        "endEarly": "提前结束本次记录",
        "pass": "达标",
        "low": "偏少"
      },
      "common": {
        "recentContractions": "最近的宫缩",
        "timeToGoToThe": "🚨 该去医院了",
        "511PatternReached": "已达到 5-1-1 规律"
      },
      "feed": {
        "feedsInLast24Hrs": "过去 24 小时喂养次数",
        "lastFeed": "上次喂养",
        "logAFeeding": "+ 记录一次喂养",
        "feedLog": "喂养记录",
        "feedLogged": "喂养已记录",
        "noFeeds": "还没有喂养记录。",
        "fewFeedsTitle": "⚠ 今天喂养不足 8 次",
        "fewFeedsBody": "新生儿通常每 24 小时需要喂养 8–12 次。如果宝宝很难叫醒或体重没有增长，请联系你的医生。",
        "breast": "🤱 母乳",
        "bottle": "🍼 奶瓶",
        "minutes": "{n} 分钟"
      },
      "diaper": {
        "wetToday": "今天尿湿",
        "dirtyToday": "今天大便",
        "bothWetDirty": "+ 两者都有（尿湿和大便）",
        "whatToExpectByAge": "按日龄的正常范围",
        "day1212": "第 1–2 天：1–2 片尿湿 · 第 3–4 天：3–4 片尿湿 · 第 5 天起：6 片以上尿湿、每天 3–4 次大便。第 5 天后尿湿少于 6 片 → 请联系你的医生。",
        "todaySLog": "今天的记录",
        "noDiapers": "今天还没有尿布记录。"
      },
      "jaundice": {
        "babySBirthDate": "宝宝的出生日期",
        "set": "保存",
        "birthDateSaved": "出生日期已保存",
        "dayOfLife": "出生天数",
        "resolvesByNow": "多数黄疸在此时已消退",
        "callImmediatelyIf": "出现以下情况请立即联系医生",
        "setBirthDateHint": "在上方填写宝宝的出生日期，即可查看逐日指导。",
        "day1": "第 1 天，出院前会检查胆红素。护理人员会观察宝宝。",
        "day2": "胆红素水平正在上升。出院前医院会做检查。注意观察皮肤和眼白是否发黄。",
        "day3": "多数宝宝的黄疸在第 3–5 天达到高峰。黄色可能更明显。频繁哺乳（每天 8–12 次）有助于身体排出胆红素。",
        "day4": "黄疸高峰期。确保宝宝吃得好、尿布有尿。儿科随访通常安排在这几天。",
        "day5": "儿科就诊：称体重并测胆红素。水平应开始趋于平稳。如果宝宝嗜睡、不肯吃奶，请联系医生。",
        "day6": "足月宝宝的胆红素应开始下降。继续频繁哺乳。如果皮肤明显发黄，或宝宝叫不醒吃奶，请联系医生。",
        "day7": "多数足月宝宝的黄疸此时正在好转。注意黄色是否扩散到腿部和脚部，这提示水平偏高。",
        "day10": "多数足月宝宝的黄疸已基本消退。如果持续或加重，医生会想复查胆红素。",
        "day14": "2 周随访。足月宝宝的黄疸应已消退。超过 2 周仍未消退可能需要进一步检查，请告诉医生。",
        "day21": "黄疸持续超过 3 周属于迁延性黄疸，应当评估。母乳喂养的宝宝轻度黄疸可能持续更久，但仍需检查。",
        "dayWatch": "第 {day} 天，需要留意",
        "redFlags": "宝宝叫不醒吃奶 · 明显发黄并扩散到腿部 · 身体后弓或哭声尖锐 · 大便呈白色或灰色 · 尿色很深"
      },
      "bp": {
        "logBloodPressure": "+ 记录血压",
        "whenToCallYourDoctor": "什么时候要联系医生",
        "anyReading14090During": "怀孕期间或产后任何一次 ≥ 140/90 的读数。≥ 160/110 属于急症，请拨打产房（L&D）电话或 911。",
        "readings": "血压读数",
        "enterValidNumbersEG": "请输入有效数字（例如 118 / 76）",
        "highReadingContactYourDoctor": "血压偏高，请联系你的医生",
        "noReadings": "还没有血压记录。",
        "highOnRecord": "⚠ 记录到偏高读数",
        "cat": {
          "severe": "重度偏高",
          "high": "偏高",
          "elevated": "临界偏高",
          "normal": "正常"
        },
        "recentSummary": "你最近一次读数（{reading}）处于「{cat}」范围。请今天联系你的医生。",
        "savedReading": "已保存 {reading} · {cat}"
      },
      "weight": {
        "yourProfile": "你的基本信息",
        "prePregnancyWeightLbs": "孕前体重（lbs）",
        "prePregnancyBmi": "孕前 BMI",
        "saveProfile": "保存信息",
        "logWeight": "+ 记录体重",
        "weightLog": "体重记录",
        "profileSaved": "信息已保存",
        "enterValidWeightAndPregnancy": "请输入有效的体重和孕周",
        "noWeights": "还没有体重记录。",
        "recommendedGain": "建议总增重：",
        "forFullPregnancy": "为整个孕期的建议值。",
        "setYourProfile": "设置你的基本信息",
        "setProfileHint": "输入孕前 BMI，即可查看为你定制的 IOM 增重建议。",
        "bmi": {
          "under": "体重偏低",
          "normal": "体重正常",
          "over": "超重",
          "obese": "肥胖"
        },
        "iomFor": "适合你的 IOM 建议（{range}）"
      },
      "appts": {
        "addVisit": "+ 添加就诊",
        "questionsToAsk": "想问的问题",
        "noneAdded": "尚未添加",
        "notesFromVisit": "就诊记录",
        "edit": "编辑",
        "delete": "删除",
        "visitDeleted": "就诊记录已删除",
        "noVisits": "还没有就诊记录。在上方添加一条，用来记录问题和笔记。",
        "deleteConfirm": "要删除这条就诊记录吗？"
      },
      "cx": {
        "noContractions": "还没有宫缩记录。<br>宫缩开始时点击「宫缩开始」。",
        "noContraction": "当前没有宫缩",
        "inProgress": "宫缩进行中…",
        "startBtn": "宫缩开始",
        "endBtn": "宫缩结束",
        "clearAll": "全部清除",
        "clearConfirm": "要清除所有宫缩记录吗？",
        "duration": "持续 {d}",
        "interval": "间隔 {t}",
        "alertGo": "宫缩间隔约 {mins} 分钟，每次约 {secs} 秒。请立即致电产房。",
        "alert511": "间隔约 {mins} 分钟，每次约 {secs} 秒。如果这是第一胎，请前往医院。破水或不确定时请致电。",
        "alertProgress": "最近一小时：间隔约 {mins} 分钟 · 每次约 {secs} 秒 · 共 {n} 次宫缩。尚未达到 5-1-1 规律。"
      },
      "i18n": {
        "intro": "把应用里的每一句话和英文原文对照一下。如果读起来不对，就写下更好的说法。你的建议只保存在这部手机上，直到你导出为止。",
        "searchPlaceholder": "搜索词句…",
        "needsWork": "待完善",
        "all": "全部",
        "suggested": "已建议",
        "suggestPlaceholder": "提出更好的说法…",
        "nothingToShow": "当前筛选条件下没有内容。",
        "showingFirst": "显示 {total} 条中的前 {n} 条。可用搜索缩小范围。",
        "export": "导出我的建议",
        "clear": "清除",
        "clearConfirm": "要删除该语言的所有建议吗？",
        "nothingToExport": "还没有可导出的建议",
        "exported": "已导出 {n} 条建议",
        "submit": "提交",
        "sending": "发送中…",
        "sent": "已发送，谢谢",
        "sentShort": "已发送 ✓",
        "typeFirst": "请先写下建议",
        "sendFailed": "发送失败，已保存在本机，请用导出",
        "rateLimited": "提交次数过多，请稍后再试",
        "offlineSaved": "离线，已保存在本机，请用导出",
        "privacy": "只会发送该词句和你的建议。你的记录数据永远不会离开这部手机。"
      },
      "improve": {
        "intro": "这本指南是人写的，读者告诉我们缺了什么，它才会变得更好。说说在你们的文化里这件事是怎么做的，问一个我们没有写到的话题，或者指出任何读起来不清楚的地方。",
        "notDoctor": "这些内容会交给编写这本指南的人。这不是联系你自己医生的渠道，这里也不会有人回复。",
        "whatKind": "你想分享什么？",
        "kindCulture": "在我们的文化里做法不一样",
        "kindQuestion": "这本指南没有回答的问题",
        "kindUnclear": "这里有些地方让我困惑",
        "topicLabel": "是关于哪一部分？（可不填）",
        "topicPlaceholder": "例如：安全睡眠、GBS、第一次洗澡",
        "messageLabel": "告诉我们",
        "messagePlaceholder": "写多写少都可以……",
        "send": "发送",
        "sending": "发送中…",
        "thanks": "谢谢你。这有助于让指南更好。",
        "writeFirst": "请先写点内容",
        "failed": "发送失败。你写的内容已保存在本机。",
        "rateLimited": "发送太频繁，请稍后再试",
        "offline": "当前离线。你写的内容已保存在本机。"
      },
      "nausea": {
        "intro": "空腹时孕吐通常更明显，所以少量多次比大餐更管用。点一下你吃过或喝过东西的时段。重点不是吃多少，而是两次之间隔了多久。",
        "clockLabel": "24 小时进食表",
        "snacksToday": "今天",
        "tapHour": "点击某个时段表示你吃过东西",
        "hourLabel": "{hour} 点",
        "longestGap": "最长的空腹时间",
        "gapOk": "{hours} 小时。醒着的时候尽量不要超过约 3 小时。",
        "gapLong": "{hours} 小时。空腹太久会加重孕吐。吃一点点也好，哪怕只有几口。",
        "whenAreYou": "你现在几周了？",
        "weekPrompt": "输入你目前的孕周，就能看到自己处在哪个阶段。",
        "weekPlaceholder": "例如 9",
        "weekShort": "第 {n} 周",
        "timelineLabel": "孕吐进程，你现在是第 {week} 周",
        "youAreWeek": "你现在是第 {week} 周。",
        "changeWeek": "修改孕周",
        "phaseEarly": "孕吐通常在第 6 周左右开始。如果还没有出现，也可能不会出现。",
        "phasePeak": "这通常是最难熬的阶段。多在第 9 到 10 周达到高峰，之后逐渐减轻。",
        "phaseEasing": "多数人从这里开始好转。大约每 10 人中有 6 人在第 14 周前已经过去了。",
        "phaseMost": "大约每 10 人中有 9 人在第 22 周前度过了最难的时候。如果你没有好转，请告诉医生。",
        "phaseLate": "这么晚还有孕吐并不常见。值得告诉医生，医生可以排查其他原因。",
        "callTodayTitle": "出现以下情况请今天就联系医生",
        "flag": {
          "noFluids": "一整天连水都喝不进、留不住",
          "vomitingOften": "每天呕吐好几次，天天如此",
          "weightLoss": "体重不增反降",
          "darkUrine": "尿色很深，或者 8 小时没有小便",
          "dizzy": "站起来时头晕或快要昏倒",
          "racingHeart": "心跳很快"
        },
        "callTodayBody": "严重的孕期呕吐有个名字，叫妊娠剧吐，是可以治疗的。真正危险的是脱水，而不是恶心本身。不要硬撑。",
        "strat": {
          "empty": {
            "name": "别让胃空着",
            "how": "在饿之前就吃一点，床边放些饼干，起身前先吃两口。"
          },
          "bland": {
            "name": "清淡、干爽、凉的食物",
            "how": "凉的食物气味小。干吐司、苏打饼干、白米饭、凉水果。"
          },
          "fluids": {
            "name": "两餐之间小口喝水",
            "how": "边吃边喝更容易撑。改成一天里少量多次地喝。"
          },
          "triggers": {
            "name": "找出你的诱因",
            "how": "通常是气味。炒菜、咖啡、香水。可以的话让别人做饭。"
          },
          "b6": {
            "name": "维生素 B6（吡哆醇）",
            "how": "每次 10 到 25 毫克，每天三到四次。24 小时内不超过 200 毫克。非处方即可购买。"
          },
          "ginger": {
            "name": "生姜",
            "how": "姜茶、胶囊或姜糖。证据一般，但对一些人很有用。"
          },
          "acupressure": {
            "name": "按压手腕",
            "how": "按压 P6 穴位，或戴腕带。见下面的说明。"
          },
          "vitamin": {
            "name": "换个时间吃孕期维生素",
            "how": "常见的原因是铁。改到晚上吃，或随餐吃。也可以问问低铁配方。"
          },
          "rest": {
            "name": "多休息，慢慢起身",
            "how": "疲劳会加重孕吐。起床前先在床边坐一会儿。"
          },
          "doxylamine": {
            "name": "多西拉敏，与 B6 一起用",
            "how": "睡前 12.5 毫克，也就是半片 25 毫克的 Unisom SleepTab。如果不够，医生可能会加上早晨和下午各一次。24 小时内不超过 50 毫克。要买 SleepTabs，不要买 SleepGels，后者是另一种药。不需要处方。"
          }
        },
        "thingsToTry": "可以试试",
        "tryNext": "还没试过：{thing}",
        "triedAll": "你已经把所有方法都标成试过了。如果都没用，值得打个电话。",
        "stratNote": "点一下你试过的，方便记录。开始吃补充剂或药物前请先问医生。",
        "howIsItNow": "现在孕吐怎么样？",
        "level1": "没有",
        "level2": "轻微",
        "level3": "厉害",
        "level4": "很厉害",
        "didYouTry": "你试了什么吗？（可不填）",
        "logged": "已记录",
        "whatHelpsYou": "对你有用的",
        "avgAfter": "平均 {avg} · {n} 次",
        "lowerIsBetter": "数字越低越好。这只是你自己的记录，不是医学证据。",
        "recent": "最近的记录",
        "noEntries": "还没有记录。多记几次，这里就会显示什么对你有用。",
        "acuTitle": "按压手腕（P6 内关穴）",
        "acuIntro": "证据不一，但不花钱、没有副作用，对一些人有效。值得花十分钟试试。",
        "acuBands": "晕车晕船用的、带一颗塑料凸点的弹力腕带，按的就是同一个位置。两只手腕各戴一只。",
        "acu": {
          "find": "一只手掌心朝上，手指放松。",
          "measure": "用另一只手的三根手指横放在手腕上，最靠近手掌的那根手指压在手与手臂交接的横纹上。",
          "feel": "穴位就在第三根手指的稍上方，位于手腕正中。按一按，会摸到两条沿手臂延伸的硬筋，穴位就在这两条筋之间。",
          "press": "用拇指用力按压，力度到能明显感觉到但不疼。可以画小圈或持续按压，做两到三分钟。",
          "both": "另一只手腕同样做一次。恶心加重时随时重复。"
        },
        "logIntro": "孕吐有变化时就记一次。记几次之后，这里会显示你试过的方法里哪一个真的对你有用。",
        "openLog": "记录现在的感觉",
        "openHelp": "孕吐可以试试这些"
      }
    },
    "theme": {
      "toggle": "切换深色模式"
    },
    "lang": {
      "label": "语言",
      "change": "切换语言",
      "unreviewedNotice": "此翻译由机器生成，尚未经过医务人员审核。做出医疗决定前，请与你的医疗团队确认，或切换到英文。",
      "loadFailed": "加载失败",
      "inProgress": "翻译进行中"
    },
    "app": {
      "title": "怀孕手册",
      "tagline": "",
      "description": "循证的怀孕、分娩、生产与产后指南。可离线使用。",
      "home": "首页",
      "prenatal": "产前",
      "labor": "分娩",
      "recovery": "恢复",
      "baby": "宝宝",
      "faq": "问答",
      "tools": "工具",
      "offlineBanner": "⚠ 你已离线，所有内容仍可查看",
      "searchPlaceholder": "搜索全部主题…"
    },
    "home": {
      "myInfoContacts": "我的信息<br>与联系人",
      "saveYourCareTeamContacts": "保存你的医疗团队联系方式",
      "tapToCallOrText": "点击即可直接从应用拨打电话或发短信",
      "callYourDoctorIf": "出现以下情况请联系医生…",
      "duringPregnancy": "怀孕期间",
      "vaginalBleeding": "阴道出血",
      "fluidGushingOrTrickling": "羊水涌出或渗漏",
      "babyNotMovingNormally": "胎动不如平时",
      "severeHeadache": "剧烈头痛",
      "visionChanges": "视力改变",
      "suddenSwellingOfFaceHands": "面部或手部突然肿胀",
      "fever1004F": "发热 &gt;100.4°F",
      "contractionsBefore37Weeks": "不足 37 周出现宫缩",
      "afterDelivery": "分娩之后",
      "soaking1PadHr2": "每小时湿透 1 片以上卫生巾 × 持续 2 小时",
      "woundOpensOrOozes": "伤口裂开或渗液",
      "legRednessSwelling": "腿部发红或肿胀",
      "chestPainOrTroubleBreathing": "胸痛或呼吸困难",
      "thoughtsOfSelfHarm": "有伤害自己的念头",
      "heroTitle": "了解会发生<br>什么。问出好<br>问题。",
      "heroDesc": "从第一次产检到分娩和恢复，Obiana 把所有内容都放在一处。"
    },
    "pregnancy": {
      "section1": "第 1 部分",
      "prenatalVisitsPregnancy": "产前检查<br>与怀孕",
      "aVisitByVisitGuide": "逐次产检指南、宫颈检查说明、孕期运动，以及每个阶段该问些什么。"
    },
    "labor": {
      "section2": "第 2 部分",
      "laborDelivery": "分娩<br>与生产",
      "signsOfLaborWhatHappens": "临产征兆、到院后会发生什么、镇痛选择、剖腹产，以及高危妊娠的照护。"
    },
    "recovery": {
      "section3": "第 3 部分",
      "postpartumRecovery": "产后<br>恢复",
      "physicalHealingMoodAndPpd": "身体恢复、情绪与产后抑郁、盆腔休息、恢复运动，以及什么时候可以回家。"
    },
    "baby": {
      "section4": "第 4 部分",
      "yourNewborn": "你的<br>新生儿",
      "breastfeedingFormulaCordCareSafe": "母乳喂养、配方奶、脐带护理、安全睡眠、新生儿的正常外观，以及后续复诊。"
    },
    "tools": {
      "dailyTools": "日常工具",
      "trackersPlanners": "记录<br>与计划工具",
      "timeContractionsCountKicksLog": "计时宫缩、数胎动、记录喂养和尿布、监测血压、规划分娩，以及更多功能。",
      "labor": "分娩",
      "kickCounter": "胎动计数器",
      "10MovesIn2Hours": "2 小时内 10 次胎动，记录与历史",
      "contractionTimer": "宫缩计时器",
      "tapStartStop51": "点击开始/停止 · 5-1-1 提醒 · 何时去医院",
      "newbornPostpartum": "新生儿与产后",
      "feedingLog": "喂养记录",
      "breastOrBottle24Hr": "母乳或奶瓶 · 24 小时计数 · 次数偏少时提醒",
      "diaperLog": "尿布记录",
      "wetDirtyCountDailyTotals": "尿湿与大便计数 · 每日汇总供医生查看",
      "jaundiceTracker": "黄疸追踪",
      "dayByDayGuidanceFrom": "从出生起逐日指导",
      "moodCheckIn": "情绪自评",
      "epdsScreenWeeklyTrackingFlags": "EPDS 筛查 · 每周追踪 · 提示需关注的情况",
      "pregnancyMonitoring": "孕期监测",
      "bloodPressure": "血压",
      "logReadingsFlags14090": "记录读数 · 自动标记 ≥ 140/90",
      "weightTracker": "体重追踪",
      "logByWeekIomGain": "按孕周记录 · 依据你的 BMI 给出 IOM 增重建议",
      "planning": "计划",
      "birthPlanBuilder": "分娩计划工具",
      "guidedChoicesShareableOnePage": "引导式选择 · 可分享的一页摘要",
      "visitNotes": "就诊笔记",
      "questionsBeforeNotesDuringEvery": "就诊前的问题 · 每次就诊的记录",
      "translationHelper": "翻译助手",
      "reviewSuggestWording": "检查用词 · 提出更好的翻译",
      "improveGuide": "帮助改进这本指南",
      "shareCustomAsk": "说说你们的文化怎么做 · 问任何不清楚的地方",
      "helpUsImprove": "帮助我们改进",
      "nauseaHelper": "孕吐与进食",
      "nauseaHelperDesc": "进食节奏 · 可以试试 · 手腕按压",
      "feelingWell": "照顾自己",
      "nauseaLog": "孕吐记录",
      "nauseaLogDesc": "打分 · 记下试过什么 · 看看什么有效"
    },
    "toolkick": {
      "kickCounter": "胎动计数器"
    },
    "toolcontractions": {
      "contractionTimer": "宫缩计时器"
    },
    "toolfeeding": {
      "feedingLog": "喂养记录"
    },
    "tooldiapers": {
      "diaperLog": "尿布记录"
    },
    "tooljaundice": {
      "jaundiceTracker": "黄疸追踪"
    },
    "toolbp": {
      "bloodPressureLog": "血压记录"
    },
    "toolweight": {
      "weightTracker": "体重追踪"
    },
    "toolmood": {
      "moodCheckIn": "情绪自评"
    },
    "toolbirthplan": {
      "birthPlanBuilder": "分娩计划工具"
    },
    "toolappts": {
      "visitNotes": "就诊笔记"
    },
    "modalFeed": {
      "logAFeeding": "记录一次喂养",
      "type": "方式",
      "breast": "🤱 母乳",
      "bottle": "🍼 奶瓶",
      "side": "哪一侧",
      "left": "左侧",
      "right": "右侧",
      "both": "两侧",
      "durationMinutes": "时长（分钟）",
      "amountOz": "奶量（oz）",
      "saveFeed": "保存喂养记录"
    },
    "modalBp": {
      "logBloodPressure": "记录血压",
      "systolicTop": "收缩压（上面的数字）",
      "diastolicBottom": "舒张压（下面的数字）",
      "normalRange": "正常范围",
      "below12080IsNormal": "低于 120/80 属正常。怀孕期间 ≥ 140/90 需当天就医处理。",
      "saveReading": "保存读数"
    },
    "modalWeight": {
      "logWeight": "记录体重",
      "weightLbs": "体重（lbs）",
      "weekOfPregnancy": "孕周",
      "save": "保存"
    },
    "modalAppt": {
      "addVisit": "添加就诊",
      "visitType": "就诊类型",
      "date": "日期",
      "questionsToAskBeforehand": "就诊前想问的问题",
      "notesFromVisit": "就诊记录",
      "saveVisit": "保存就诊"
    },
    "apptType": {
      "selectType": "选择类型…",
      "obRoutine": "产科 – 常规产检",
      "obTriage": "产科 – 产房分诊（L&amp;D）/ 临时就诊",
      "mfmConsult": "母胎医学（MFM）会诊",
      "mfmFollowup": "母胎医学（MFM）复诊",
      "endo": "内分泌科",
      "cardio": "心脏科",
      "nephro": "肾科",
      "ultrasound": "超声检查",
      "nst": "无应激试验（NST）",
      "lactation": "哺乳咨询",
      "pp2wk": "产后 – 2 周",
      "pp6wk": "产后 – 6 周",
      "peds25d": "儿科 – 出生后 2–5 天",
      "peds2wk": "儿科 – 2 周",
      "peds2mo": "儿科 – 2 个月",
      "family": "家庭医生",
      "other": "其他"
    },
    "install": {
      "addToPhone": "添加到手机"
    },
    "common": {
      "toolsBack": "工具"
    },
    "nav": {
      "prenatal": "产前<br>检查",
      "labor": "分娩<br>与生产",
      "recovery": "产后<br>恢复",
      "baby": "你的<br>新生儿",
      "toolsTrackers": "工具<br>与记录"
    },
    "tooli18n": {
      "translationHelper": "翻译助手"
    },
    "usNotice": {
      "title": "在美国接受的照护",
      "body": "本指南描述的是美国提供的产前照护，写给在美国接受照护的准妈妈。各国的产前照护差异很大。其他国家的产检安排、检查项目和建议，可能与这里写的不同。如果你在其他国家接受照护，这个应用可能并不适合你。",
      "continue": "我明白了"
    },
    "toolimprove": {
      "improveGuide": "帮助改进这本指南"
    },
    "about": {
      "openSource": "自由开源软件。欢迎分支，但请保持自由开源。",
      "viewSource": "查看源代码（AGPL-3.0）"
    },
    "toolnausea": {
      "nauseaEating": "孕吐与进食"
    },
    "toolnausealog": {
      "nauseaLog": "孕吐记录"
    }
  }
};
