// ═══════════════════════════════════════════════════════
// LOCALE: ko
// ═══════════════════════════════════════════════════════
// MACHINE TRANSLATED — generated by translation/run-kimi.sh and merged by
// translation/merge.js. Not yet reviewed by a clinician.
//
// reviewed:false drives the machine-translation notice shown to the patient.
// Do NOT flip it to true until someone qualified has read this content.
//
// Any key omitted here falls back to English at runtime.
//
// No `epds` block: the Edinburgh scale is gated off for this language.
// Never machine-translate the EPDS — see TRANSLATING.md.

window.MYOB_LOCALES = window.MYOB_LOCALES || {};

window.MYOB_LOCALES.ko = {
  "reviewed": false,
  "translationStatus": "machine",
  "ui": {
    "section": {
      "pregnancy": "임신 중 관리",
      "labor": "분만",
      "recovery": "회복",
      "baby": "신생아",
      "faq": "자주 묻는 질문"
    },
    "faq": {
      "badgeMyth": "속설",
      "badgeFaq": "자주 묻는 질문",
      "section5": "제5부",
      "faqCommonMyths": "자주 묻는 질문 &amp;<br>흔한 속설",
      "evidenceBasedAnswersToThe": "가장 흔한 질문에 대한 근거 기반 답변입니다. 가족, 친구, 인터넷에서 들으신 이야기도 함께 다룹니다."
    },
    "search": {
      "noResultsTitle": "검색 결과가 없습니다",
      "noResultsHint": "다른 검색어를 써 보세요. 예: \"무통주사\", \"제대 관리\", \"출혈\"",
      "resultCount": {
        "other": "“{q}” 검색 결과 {count}개"
      }
    },
    "myinfo": {
      "namePlaceholder": "이름",
      "phonePlaceholder": "전화번호",
      "call": "전화",
      "text": "문자",
      "contact": {
        "familydoc": "가정의",
        "ob": "산부인과 의사 / 조산사",
        "peds": "소아과 의사",
        "mfm": "MFM(모체태아의학) 전문의",
        "lactation": "모유수유 상담사",
        "ld": "병원 / L&D(분만실) 분류",
        "pharmacy": "약국"
      },
      "detail": {
        "edd": {
          "label": "출산 예정일 (EDD)",
          "placeholder": "예: 2026년 7월 15일"
        },
        "bloodtype": {
          "label": "혈액형 및 Rh 요인",
          "placeholder": "예: O형 양성"
        },
        "gbs": {
          "label": "GBS(B군 연쇄상구균) 검사 결과",
          "placeholder": "양성 / 음성 / 아직 검사 전"
        },
        "allergies": {
          "label": "약물 알레르기",
          "placeholder": "예: 페니실린"
        },
        "insurance": {
          "label": "보험 / 회원 ID",
          "placeholder": "병원에서 빠르게 확인할 수 있도록"
        }
      },
      "myInformation": "내 정보",
      "myCareTeamKeyDetails": "내 진료팀 &amp;<br>주요 정보",
      "savedOnYourPhoneTap": "휴대폰에 저장됨 · 눌러서 전화 또는 문자",
      "careTeamContacts": "진료팀 연락처",
      "myPregnancyDetails": "내 임신 정보",
      "questionsForMyDoctor": "의사에게 물어볼 질문",
      "saveMyInformation": "내 정보 저장",
      "exportData": "데이터보내기"
    },
    "toast": {
      "contactsSaved": "연락처가 휴대폰에 저장되었습니다",
      "appInstalled": "앱이 설치되었습니다! 홈 화면에서 언제든 여세요",
      "dataExported": "데이터를보냈습니다!",
      "appUpdated": "앱이 업데이트되었습니다. 최신 버전을 보려면 새로고침하세요"
    },
    "tool": {
      "mood": {
        "unavailableTitle": "이 언어로는 기분 체크를 이용할 수 없습니다",
        "unavailableBody": "에딘버러 산후 우울 척도(EPDS)는 검증된 선별 설문지입니다. 공식적으로 검증된 번역본으로만 점수가 의미가 있으므로, 기계 번역본은 제공하지 않습니다.",
        "availableIn": "현재 이용 가능한 언어: {langs}. 사용하시는 언어의 검증된 버전에 대해 진료팀에 문의해 주세요.",
        "switchToEnglish": "영어로 전환",
        "qCounter": "{total}개 중 {n}번째 질문",
        "answerAll": "{total}개 질문에 모두 답해 주세요",
        "interpLow": "걱정 수준 낮음",
        "interpConcern": "의사와 상담해 보는 것이 좋습니다",
        "interpHigh": "의사에게 연락해 주세요",
        "edinburghPostnatalDepressionScale": "에딘버러 산후 우울 척도 (EPDS)",
        "inThePast7Days": "지난 7일 동안",
        "yourAnswersAreSavedOnly": "답변은 이 휴대폰에만 저장됩니다.",
        "getMyScore": "내 점수 확인",
        "scoreOutOf30Based": "총점 30점 만점 · 에딘버러 산후 우울 척도 기반",
        "pastCheckIns": "이전 검사 기록",
        "selfHarmGuidance": "스스로를 해치고 싶은 생각이 들었다고 답하셨습니다. 담당 의료진에게 연락하시거나 988(자살 예방 및 위기 상담 전화)로 전화 또는 문자하시거나, 가까운 응급실을 방문하세요.",
        "continueWeekly": "매주 계속 확인해 보세요. 기분이 달라지면 이 도구로 추적할 수 있습니다.",
        "talkToDoctor": "선별 점수에 대해서라도 의료진과 이야기하는 것은 언제나 좋은 일입니다. 산후우울증은 치료가 잘 됩니다.",
        "instrumentLanguage": "설문지 언어:",
        "change": "변경",
        "scoreNote": "{max}점 만점 · {instrument} · 진단이 아니라 선별 도구입니다. 결과는 반드시 의료진과 상의하세요",
        "chooseLanguage": "답변하실 언어를 선택하세요:",
        "validatedOnlyNote": "공식적으로 검증된 판만 제공합니다. 기계 번역도 점수는 나오지만 그 점수는 의미가 없습니다."
      },
      "birthplan": {
        "q": {
          "epidural": {
            "label": "통증 완화 방법 선호도",
            "opt": {
              "epidural": "예, 무통주사(경막외 마취)",
              "none": "약물 사용 안 함",
              "open": "모든 선택지를 열어 둠",
              "iv": "정맥(IV) 약물만"
            }
          },
          "mobility": {
            "label": "진통 중 움직임",
            "opt": {
              "walk": "걷거나 움직이고 싶음",
              "bed": "침대에 누워 있고 싶음",
              "wireless": "가능하면 무선 모니터 사용"
            }
          },
          "delayed-cord": {
            "label": "제대 자르기 지연 (30–60초)",
            "opt": {
              "yes": "예, 해 주세요",
              "nopref": "상관없음",
              "discuss": "진료팀과 상담"
            }
          },
          "skin-to-skin": {
            "label": "출산 직후 피부 맞대기",
            "opt": {
              "top": "예, 최우선",
              "ifposs": "가능하다면 예",
              "nopref": "상관없음"
            }
          },
          "pushing": {
            "label": "힘주기 자세",
            "opt": {
              "nurse": "간호사의 안내에 따름",
              "positions": "여러 자세를 시도해 보고 싶음",
              "squat": "스쿼트 자세/선 자세"
            }
          },
          "episiotomy": {
            "label": "회음부 절개",
            "opt": {
              "avoid": "꼭 필요한 경우가 아니면 피하고 싶어요",
              "trust": "의료진의 판단을 따르겠어요",
              "nopref": "상관없어요"
            }
          },
          "cord-cut": {
            "label": "제대를 자를 사람",
            "opt": {
              "support": "동반자",
              "team": "의료진",
              "nopref": "상관없어요"
            }
          },
          "photos": {
            "label": "분만 중 사진 촬영",
            "opt": {
              "yes": "촬영해 주세요",
              "none": "분만 중 사진 촬영은 원하지 않아요",
              "after": "분만 후에만 촬영해 주세요"
            }
          },
          "visitors": {
            "label": "진통 중 방문객",
            "opt": {
              "supportonly": "동반자만 허용",
              "family": "가까운 가족은 환영해요",
              "none": "방문객은 받지 않을래요"
            }
          },
          "breastfeed": {
            "label": "수유 계획",
            "opt": {
              "exclusive": "모유만 수유",
              "supplement": "모유 수유 + 보충 수유",
              "formula": "분유만 수유",
              "unsure": "아직 잘 모르겠어요"
            }
          },
          "csection": {
            "label": "제왕절개가 필요한 경우",
            "opt": {
              "lowscreen": "차단막을 낮게 (아기 볼 수 있게)",
              "supportor": "동반자 수술실 동행",
              "skinor": "가능하면 수술실에서 피부 맞대기",
              "standard": "일반적인 방식으로 해주세요"
            }
          },
          "music": {
            "label": "분위기",
            "opt": {
              "playlist": "음악 / 내 재생목록",
              "quiet": "조용한 환경",
              "nopref": "상관없어요"
            }
          }
        },
        "additionalNotesComments": "추가 메모 / 코멘트",
        "copyToShare": "복사해서 공유하기",
        "printPdf": "인쇄 / PDF",
        "additionalNotes": "추가 메모:",
        "myBirthPreferences": "나의 분만 희망사항",
        "pregnancyBirthGuideEvidenceBased": "임신 &amp; 출산 가이드 · 근거 기반 · 비공개 &amp; 오프라인",
        "anyOtherPreferencesConcernsOr": "의료진에게 전달할 다른 희망사항, 걱정, 정보가 있으면 적어 주세요…",
        "copiedToClipboard": "클립보드에 복사했어요!",
        "copyNotSupportedOnThis": "이 브라우저에서는 복사를 지원하지 않아요",
        "selectPreferences": "아래에서 원하는 항목을 선택하세요. 요약이 아래에 표시되며 의료진과 공유할 수 있습니다.",
        "generatedOn": "{date} 생성"
      },
      "kick": {
        "startSession": "세션 시작",
        "movementsThisSession": "이번 세션 움직임",
        "elapsed": "경과 시간:",
        "20000Limit": "2:00:00 제한",
        "lessThan10MovementsIn": "⚠ 2시간 동안 움직임이 10회 미만이에요",
        "thisMayNeedAttentionCall": "확인이 필요할 수 있어요. 의사에게 전화하세요.",
        "10MovementsReached": "10회 움직임 도달!",
        "startAnotherSession": "새 세션 시작",
        "sessionHistory": "세션 기록",
        "noSessions": "아직 세션이 없어요",
        "countMovements": "활동 중인 세션 동안 태동을 세어 보세요.",
        "goal": "목표: 2시간 안에 10회 태동",
        "tapForEach": "👶 태동마다 누르세요",
        "endEarly": "세션 일찍 끝내기",
        "pass": "달성",
        "low": "부족"
      },
      "common": {
        "recentContractions": "최근 진통",
        "timeToGoToThe": "🚨 병원에 갈 시간이에요",
        "511PatternReached": "5-1-1 패턴 도달"
      },
      "feed": {
        "feedsInLast24Hrs": "최근 24시간 수유 횟수",
        "lastFeed": "마지막 수유",
        "logAFeeding": "+ 수유 기록하기",
        "feedLog": "수유 기록",
        "feedLogged": "수유를 기록했어요",
        "noFeeds": "아직 기록된 수유가 없어요.",
        "fewFeedsTitle": "⚠ 오늘 수유 횟수가 8회 미만입니다",
        "fewFeedsBody": "신생아는 보통 24시간에 8~12회 수유가 필요합니다. 아기를 깨우기 어렵거나 체중이 늘지 않는다면 담당 의료진에게 연락하세요.",
        "breast": "🤱 모유",
        "bottle": "🍼 젖병",
        "minutes": "{n}분"
      },
      "diaper": {
        "wetToday": "오늘 소변 기저귀",
        "dirtyToday": "오늘 대변 기저귀",
        "bothWetDirty": "+ 둘 다 (소변 &amp; 대변)",
        "whatToExpectByAge": "월령별 예상 횟수",
        "day1212": "생후 1–2일: 소변 기저귀 1–2회 · 생후 3–4일: 소변 3–4회 · 생후 5일 이후: 하루 소변 6회 이상, 대변 3–4회. 생후 5일 이후 소변 기저귀가 6회 미만이면 → 의사에게 전화하세요.",
        "todaySLog": "오늘의 기록",
        "noDiapers": "오늘 기록된 기저귀가 없어요."
      },
      "jaundice": {
        "babySBirthDate": "아기 생년월일",
        "set": "설정",
        "birthDateSaved": "생년월일을 저장했어요",
        "dayOfLife": "생후 일수",
        "resolvesByNow": "대부분의 황달은 이 시기에 좋아집니다",
        "callImmediatelyIf": "다음의 경우 즉시 의료진에게 연락하세요",
        "setBirthDateHint": "위에 아기의 생년월일을 입력하면 날짜별 안내를 볼 수 있습니다.",
        "day1": "첫째 날. 퇴원 전에 빌리루빈 수치를 확인합니다. 간호진이 아기를 관찰합니다.",
        "day2": "빌리루빈 수치가 올라가는 시기입니다. 퇴원 전 병원에서 확인합니다. 피부와 눈 흰자위가 노래지는지 살펴보세요.",
        "day3": "대부분의 아기에서 황달은 생후 3~5일경 가장 심해집니다. 노란색이 더 뚜렷해질 수 있습니다. 자주 수유하면(하루 8~12회) 빌리루빈 배출에 도움이 됩니다.",
        "day4": "황달이 가장 심한 시기입니다. 아기가 잘 먹고 소변 기저귀가 충분한지 확인하세요. 이 무렵 소아과 진료가 예약되어 있을 수 있습니다.",
        "day5": "소아과 진료: 체중 확인과 빌리루빈 수치 검사. 수치가 안정되기 시작해야 합니다. 아기가 처지고 잘 먹지 않으면 의료진에게 연락하세요.",
        "day6": "만삭아에서는 수치가 떨어지기 시작해야 합니다. 계속 자주 수유하세요. 피부가 진하게 노랗거나 아기가 먹으려고 깨지 않으면 의료진에게 연락하세요.",
        "day7": "대부분의 만삭아는 이 시기에 황달이 좋아지고 있습니다. 노란색이 다리와 발까지 퍼지는지 살펴보세요. 수치가 높다는 신호입니다.",
        "day10": "대부분의 만삭아에서 황달은 거의 사라집니다. 계속되거나 심해지면 의료진이 빌리루빈 수치를 확인하려 할 것입니다.",
        "day14": "2주 진료. 만삭아에서는 황달이 사라져 있어야 합니다. 2주가 지나도 황달이 남아 있으면 추가 검사가 필요할 수 있으니 의료진에게 알리세요.",
        "day21": "3주를 넘겨 지속되는 황달은 지연 황달로 보고 평가가 필요합니다. 모유 수유아는 가벼운 황달이 더 오래갈 수 있지만 그래도 확인해야 합니다.",
        "dayWatch": "{day}일째. 살펴볼 점",
        "redFlags": "아기가 먹으려고 깨지 않음 · 진한 노란색이 다리까지 번짐 · 등을 뒤로 젖히거나 높은 톤으로 욺 · 흰색 또는 회색 변 · 매우 진한 소변"
      },
      "bp": {
        "logBloodPressure": "+ 혈압 기록하기",
        "whenToCallYourDoctor": "의사에게 전화해야 할 때",
        "anyReading14090During": "임신 중이나 산후에 혈압이 140/90 이상인 경우. 160/110 이상은 의료 응급상황이에요. L&D(분만실) 또는 911에 전화하세요.",
        "readings": "측정 기록",
        "enterValidNumbersEG": "올바른 숫자를 입력하세요 (예: 118 / 76)",
        "highReadingContactYourDoctor": "혈압이 높아요. 의사에게 연락하세요",
        "noReadings": "아직 기록된 측정값이 없어요.",
        "highOnRecord": "⚠ 높은 혈압이 기록되었습니다",
        "cat": {
          "severe": "매우 높음",
          "high": "높음",
          "elevated": "약간 높음",
          "normal": "정상"
        },
        "recentSummary": "가장 최근 측정값({reading})은 {cat} 범위입니다. 오늘 중으로 의료진에게 연락하세요.",
        "savedReading": "{reading} 저장됨 · {cat}"
      },
      "weight": {
        "yourProfile": "내 프로필",
        "prePregnancyWeightLbs": "임신 전 체중 (lbs)",
        "prePregnancyBmi": "임신 전 BMI",
        "saveProfile": "프로필 저장",
        "logWeight": "+ 체중 기록",
        "weightLog": "체중 기록",
        "profileSaved": "프로필이 저장되었습니다",
        "enterValidWeightAndPregnancy": "올바른 체중과 임신 주수를 입력해 주세요",
        "noWeights": "아직 기록된 체중이 없습니다.",
        "recommendedGain": "권장 총 체중 증가:",
        "forFullPregnancy": "임신 기간 전체 기준입니다.",
        "setYourProfile": "프로필을 설정하세요",
        "setProfileHint": "임신 전 BMI를 입력하면 맞춤 IOM 체중 증가 지침을 볼 수 있습니다.",
        "bmi": {
          "under": "저체중",
          "normal": "정상 체중",
          "over": "과체중",
          "obese": "비만"
        },
        "iomFor": "회원님을 위한 IOM 지침 ({range})"
      },
      "appts": {
        "addVisit": "+ 진료 추가",
        "questionsToAsk": "물어볼 질문",
        "noneAdded": "추가된 항목 없음",
        "notesFromVisit": "진료 메모",
        "edit": "수정",
        "delete": "삭제",
        "visitDeleted": "진료 기록이 삭제되었습니다",
        "noVisits": "아직 기록된 진료가 없습니다. 위에서 추가해 질문과 메모를 관리하세요.",
        "deleteConfirm": "이 진료 기록을 삭제할까요?"
      },
      "cx": {
        "noContractions": "아직 기록된 진통이 없습니다.<br>진통이 시작되면 \"진통 시작\"을 눌러 주세요.",
        "noContraction": "진행 중인 진통 없음",
        "inProgress": "진통 진행 중…",
        "startBtn": "진통 시작",
        "endBtn": "진통 종료",
        "clearAll": "모두 지우기",
        "clearConfirm": "모든 진통 기록을 지울까요?",
        "duration": "{d} 지속",
        "interval": "{t} 간격",
        "alertGo": "진통 간격 약 {mins}분, 지속 약 {secs}초입니다. 지금 분만실에 전화하세요.",
        "alert511": "간격 약 {mins}분, 지속 약 {secs}초입니다. 첫 출산이라면 병원으로 가세요. 양수가 터지거나 확실하지 않으면 전화하세요.",
        "alertProgress": "지난 1시간: 약 {mins}분 간격 · 약 {secs}초 지속 · 진통 {n}회. 아직 5-1-1 패턴에 도달하지 않았습니다."
      },
      "i18n": {
        "intro": "이 앱의 모든 문구를 영어 원문과 비교해 보세요. 어색한 부분이 있으면 더 나은 표현을 입력하세요. 제안은 내보내기 전까지 이 휴대폰에만 저장됩니다.",
        "searchPlaceholder": "문구 검색…",
        "needsWork": "확인 필요",
        "all": "전체",
        "suggested": "제안함",
        "suggestPlaceholder": "더 나은 표현을 제안해 주세요…",
        "nothingToShow": "이 조건에 해당하는 항목이 없습니다.",
        "showingFirst": "{total}개 중 처음 {n}개를 표시합니다. 검색으로 범위를 좁혀 보세요.",
        "export": "내 제안 내보내기",
        "clear": "지우기",
        "clearConfirm": "이 언어의 제안을 모두 삭제할까요?",
        "nothingToExport": "아직 내보낼 제안이 없습니다",
        "exported": "제안 {n}개를 내보냈습니다",
        "submit": "보내기",
        "sending": "보내는 중…",
        "sent": "전송됨. 감사합니다",
        "sentShort": "전송됨 ✓",
        "typeFirst": "먼저 제안을 입력하세요",
        "sendFailed": "보내지 못했습니다. 여기에 저장되었으니 내보내기를 사용하세요",
        "rateLimited": "너무 많이 보냈습니다. 나중에 다시 시도하세요",
        "offlineSaved": "오프라인. 여기에 저장됨, 내보내기를 사용하세요",
        "privacy": "문구와 제안만 전송됩니다. 기록된 건강 정보는 이 휴대폰을 떠나지 않습니다."
      },
      "improve": {
        "intro": "이 안내서는 사람이 씁니다. 읽는 분들이 빠진 내용을 알려주실 때 더 좋아집니다. 우리 문화에서는 어떻게 하는지 들려주시거나, 다루지 않은 주제를 물어보시거나, 이해하기 어려웠던 부분을 알려주세요.",
        "notDoctor": "이 내용은 안내서를 만드는 사람들에게 전달됩니다. 담당 의료진에게 연락하는 방법이 아니며, 여기서 답장을 드리지는 않습니다.",
        "whatKind": "어떤 이야기를 들려주시겠어요?",
        "kindCulture": "우리 문화에서는 다르게 합니다",
        "kindQuestion": "이 안내서에 없는 질문이 있습니다",
        "kindUnclear": "이해하기 어려운 부분이 있었습니다",
        "topicLabel": "어느 부분에 대한 내용인가요? (선택)",
        "topicPlaceholder": "예: 안전한 수면, GBS, 첫 목욕",
        "messageLabel": "들려주세요",
        "messagePlaceholder": "길게 쓰셔도 짧게 쓰셔도 좋습니다…",
        "send": "보내기",
        "sending": "보내는 중…",
        "thanks": "감사합니다. 안내서를 더 좋게 만드는 데 도움이 됩니다.",
        "writeFirst": "먼저 내용을 입력해 주세요",
        "failed": "보내지 못했습니다. 입력하신 내용은 여기에 저장되었습니다.",
        "rateLimited": "메시지를 너무 많이 보내셨습니다. 나중에 다시 시도해 주세요",
        "offline": "오프라인입니다. 입력하신 내용은 여기에 저장되었습니다."
      },
      "nausea": {
        "intro": "메스꺼움은 보통 공복일 때 심해집니다. 그래서 많이 한 번보다 조금씩 자주가 낫습니다. 무언가 먹거나 마신 시간을 눌러 표시하세요. 중요한 것은 양이 아니라 사이가 얼마나 벌어지는가입니다.",
        "clockLabel": "24시간 간식 시계",
        "snacksToday": "오늘",
        "tapHour": "먹은 시간을 눌러 표시하세요",
        "hourLabel": "{hour}시",
        "longestGap": "가장 길게 안 먹은 시간",
        "gapOk": "{hours}시간입니다. 깨어 있는 동안에는 3시간 이내로 유지해 보세요.",
        "gapLong": "{hours}시간입니다. 오래 비우면 메스꺼움이 심해집니다. 몇 입이라도 조금 드셔 보세요.",
        "whenAreYou": "지금 몇 주이신가요?",
        "weekPrompt": "임신 몇 주인지 입력하시면 지금 어느 지점에 계신지 보여 드립니다.",
        "weekPlaceholder": "예: 9",
        "weekShort": "{n}주",
        "timelineLabel": "입덧 경과, 현재 {week}주",
        "youAreWeek": "지금 {week}주이십니다.",
        "changeWeek": "주수 변경",
        "phaseEarly": "입덧은 보통 6주 무렵 시작됩니다. 아직 없다면 아예 없을 수도 있습니다.",
        "phasePeak": "보통 이 시기가 가장 힘듭니다. 9~10주 무렵 가장 심해졌다가 차차 나아집니다.",
        "phaseEasing": "대부분 이 시기부터 나아지기 시작합니다. 10명 중 약 6명은 14주에는 입덧이 끝납니다.",
        "phaseMost": "10명 중 약 9명은 22주면 가장 힘든 시기를 지납니다. 나아지지 않는다면 담당 의료진에게 알리세요.",
        "phaseLate": "이 시기까지 이어지는 입덧은 흔하지 않습니다. 다른 원인을 확인할 수 있도록 담당 의료진에게 말씀하세요.",
        "callTodayTitle": "다음의 경우 오늘 중으로 의료진에게 연락하세요",
        "flag": {
          "noFluids": "하루 종일 물조차 넘기지 못할 때",
          "vomitingOften": "매일 하루에 여러 번 토할 때",
          "weightLoss": "체중이 늘지 않고 오히려 줄 때",
          "darkUrine": "소변 색이 진하거나 8시간 동안 소변을 보지 못했을 때",
          "dizzy": "일어설 때 어지럽거나 쓰러질 것 같을 때",
          "racingHeart": "심장이 몹시 빠르게 뛸 때"
        },
        "callTodayBody": "심한 임신 구토에는 임신오조라는 이름이 있고 치료가 가능합니다. 진짜 위험한 것은 메스꺼움 자체가 아니라 탈수입니다. 참고 견디지 마세요.",
        "strat": {
          "empty": {
            "name": "공복 상태를 만들지 않기",
            "how": "배고파지기 전에 조금 드시고, 일어나기 전에 먹을 크래커를 머리맡에 두세요."
          },
          "bland": {
            "name": "담백하고 마른, 차가운 음식",
            "how": "차가운 음식은 냄새가 덜 납니다. 마른 토스트, 크래커, 흰밥, 차가운 과일."
          },
          "fluids": {
            "name": "식사 사이에 조금씩 마시기",
            "how": "식사와 함께 마시면 금방 배가 부릅니다. 하루 종일 조금씩 나눠 드세요."
          },
          "triggers": {
            "name": "나를 힘들게 하는 것 알아두기",
            "how": "대개 냄새가 원인입니다. 음식 조리, 커피, 향수. 가능하면 다른 사람이 요리하게 하세요."
          },
          "b6": {
            "name": "비타민 B6",
            "how": "가장 먼저 권해지는 경우가 많습니다. 시작 전에 담당 의료진에게 용량을 확인하세요."
          },
          "ginger": {
            "name": "생강",
            "how": "차, 캡슐, 젤리 형태. 근거는 강하지 않지만 도움이 되는 분들이 있습니다."
          },
          "acupressure": {
            "name": "손목 지압",
            "how": "P6 지점을 누르거나 손목 밴드를 이용합니다. 아래 설명을 보세요."
          },
          "vitamin": {
            "name": "임신부용 비타민 복용 시점 바꾸기",
            "how": "철분이 원인인 경우가 많습니다. 밤에 드시거나 음식과 함께 드세요. 철분이 적은 제품도 문의해 보세요."
          },
          "rest": {
            "name": "쉬고, 천천히 일어나기",
            "how": "피로하면 메스꺼움이 심해집니다. 일어서기 전에 침대 가장자리에 잠시 앉아 계세요."
          },
          "doxylamine": {
            "name": "처방 치료",
            "how": "B6와 독시라민 병용은 임신 중 연구가 잘 되어 있습니다. 필요한 시점인지 담당 의료진에게 물어보세요."
          }
        },
        "thingsToTry": "시도해 볼 것",
        "tryNext": "아직 안 해보신 것: {thing}",
        "triedAll": "모두 시도한 것으로 표시하셨습니다. 그래도 나아지지 않는다면 연락해 보실 만합니다.",
        "stratNote": "해보신 것을 눌러 기록해 두세요. 영양제나 약을 시작하기 전에는 담당 의료진과 상의하세요.",
        "howIsItNow": "지금 메스꺼움은 어떠신가요?",
        "level1": "없음",
        "level2": "조금",
        "level3": "심함",
        "level4": "아주 심함",
        "didYouTry": "무언가 시도하셨나요? (선택)",
        "logged": "기록되었습니다",
        "whatHelpsYou": "나에게 도움이 된 것",
        "avgAfter": "평균 {avg} · {n}회",
        "lowerIsBetter": "낮을수록 좋습니다. 본인의 기록일 뿐 의학적 근거는 아닙니다.",
        "recent": "최근 기록",
        "noEntries": "아직 기록이 없습니다. 몇 번 기록하시면 무엇이 도움이 되는지 보여 드립니다."
      }
    },
    "theme": {
      "toggle": "다크 모드 전환"
    },
    "lang": {
      "label": "언어",
      "change": "언어 변경",
      "unreviewedNotice": "이 번역은 기계 번역으로 아직 의료진의 검토를 거치지 않았습니다. 의료 관련 결정은 담당 의료진과 확인하시거나 영어로 전환해 주세요.",
      "loadFailed": "불러올 수 없습니다",
      "inProgress": "번역 진행 중"
    },
    "app": {
      "title": "임신 핸드북",
      "tagline": "",
      "description": "근거 기반의 임신, 진통, 분만 및 산후 안내서. 오프라인에서도 사용할 수 있습니다.",
      "home": "홈",
      "prenatal": "임신 중",
      "labor": "진통",
      "recovery": "회복",
      "baby": "아기",
      "faq": "자주 묻는 질문",
      "tools": "도구",
      "offlineBanner": "⚠ 오프라인 상태입니다. 모든 콘텐츠를 계속 볼 수 있습니다",
      "searchPlaceholder": "모든 주제 검색…"
    },
    "home": {
      "myInfoContacts": "내 정보와<br>연락처",
      "saveYourCareTeamContacts": "의료진 연락처 저장",
      "tapToCallOrText": "앱에서 바로 전화 또는 문자하기",
      "callYourDoctorIf": "이런 경우 의사에게 전화하세요…",
      "duringPregnancy": "임신 중",
      "vaginalBleeding": "질 출혈",
      "fluidGushingOrTrickling": "양수가 쏟아지거나 조금씩 샐 때",
      "babyNotMovingNormally": "아기 움직임이 평소와 다를 때",
      "severeHeadache": "심한 두통",
      "visionChanges": "시야 변화",
      "suddenSwellingOfFaceHands": "얼굴/손의 갑작스러운 부종",
      "fever1004F": "열 &gt;100.4°F",
      "contractionsBefore37Weeks": "37주 이전 진통",
      "afterDelivery": "출산 후",
      "soaking1PadHr2": "1시간에 패드 1장 이상 적심 × 2시간",
      "woundOpensOrOozes": "상처가 벌어지거나 진물이 날 때",
      "legRednessSwelling": "다리의 발적/부종",
      "chestPainOrTroubleBreathing": "가슴 통증 또는 호흡 곤란",
      "thoughtsOfSelfHarm": "자해 충동",
      "heroTitle": "미리 알고,<br>좋은 질문을<br>하세요.",
      "heroDesc": "첫 산전 진료부터 분만과 회복까지, Obiana가 모든 것을 한곳에 모아 드립니다."
    },
    "pregnancy": {
      "section1": "1부",
      "prenatalVisitsPregnancy": "산전 진료와<br>임신",
      "aVisitByVisitGuide": "진료별 안내, 자궁경부 검사 설명, 임신 중 운동, 각 단계에서 물어볼 내용."
    },
    "labor": {
      "section2": "2부",
      "laborDelivery": "진통과<br>분만",
      "signsOfLaborWhatHappens": "진통의 신호, 병원 도착 후 절차, 통증 관리 방법, 제왕절개, 고위험 관리."
    },
    "recovery": {
      "section3": "3부",
      "postpartumRecovery": "산후<br>회복",
      "physicalHealingMoodAndPpd": "신체 회복, 기분 변화와 산후 우울증(PPD), 성관계 제한, 운동 재개, 퇴원 시기."
    },
    "baby": {
      "section4": "4부",
      "yourNewborn": "우리<br>신생아",
      "breastfeedingFormulaCordCareSafe": "모유 수유, 분유, 제대 관리, 안전한 수면, 정상적인 신생아의 모습, 추적 진료."
    },
    "tools": {
      "dailyTools": "일상 도구",
      "trackersPlanners": "기록과<br>계획",
      "timeContractionsCountKicksLog": "진통 시간 재기, 태동 세기, 수유와 기저귀 기록, 혈압 추적, 출산 계획 등.",
      "labor": "진통",
      "kickCounter": "태동 세기",
      "10MovesIn2Hours": "2시간에 10회 움직임. 기록과 이력",
      "contractionTimer": "진통 타이머",
      "tapStartStop51": "시작/정지 누르기 · 5-1-1 알림 · 병원 갈 시기",
      "newbornPostpartum": "신생아와 산후",
      "feedingLog": "수유 기록",
      "breastOrBottle24Hr": "모유 또는 젖병 · 24시간 횟수 · 부족 시 알림",
      "diaperLog": "기저귀 기록",
      "wetDirtyCountDailyTotals": "젖은 기저귀와 대변 횟수 · 의사에게 보여줄 하루 합계",
      "jaundiceTracker": "황달 추적",
      "dayByDayGuidanceFrom": "출생 후 날짜별 안내",
      "moodCheckIn": "기분 체크인",
      "epdsScreenWeeklyTrackingFlags": "EPDS 검사 · 매주 기록 · 문제가 있으면 알려드려요",
      "pregnancyMonitoring": "임신 중 건강 체크",
      "bloodPressure": "혈압",
      "logReadingsFlags14090": "혈압 기록 · 140/90 이상이면 자동으로 알려드려요",
      "weightTracker": "체중 기록",
      "logByWeekIomGain": "주차별 기록 · 내 BMI에 맞는 IOM 체중 증가 기준",
      "planning": "계획하기",
      "birthPlanBuilder": "출산 계획 만들기",
      "guidedChoicesShareableOnePage": "차근차근 선택하기 · 한 장짜리 요약 공유 가능",
      "visitNotes": "진료 메모",
      "questionsBeforeNotesDuringEvery": "진료 전 질문 · 매 진료마다 메모",
      "translationHelper": "번역 도우미",
      "reviewSuggestWording": "문구 검토 · 더 나은 번역 제안",
      "improveGuide": "이 안내서 개선에 도움 주기",
      "shareCustomAsk": "우리 문화에서는 어떻게 하는지 알려주기 · 궁금한 점 묻기",
      "helpUsImprove": "개선에 도움 주기",
      "nauseaHelper": "메스꺼움과 식사",
      "nauseaHelperDesc": "간식 리듬 · 시도해 볼 것 · 도움이 된 것 기록",
      "feelingWell": "컨디션 관리"
    },
    "toolkick": {
      "kickCounter": "태동 카운터"
    },
    "toolcontractions": {
      "contractionTimer": "진통 타이머"
    },
    "toolfeeding": {
      "feedingLog": "수유 기록"
    },
    "tooldiapers": {
      "diaperLog": "기저귀 기록"
    },
    "tooljaundice": {
      "jaundiceTracker": "황달 체크"
    },
    "toolbp": {
      "bloodPressureLog": "혈압 기록"
    },
    "toolweight": {
      "weightTracker": "체중 기록"
    },
    "toolmood": {
      "moodCheckIn": "기분 체크인"
    },
    "toolbirthplan": {
      "birthPlanBuilder": "출산 계획 만들기"
    },
    "toolappts": {
      "visitNotes": "진료 메모"
    },
    "modalFeed": {
      "logAFeeding": "수유 기록하기",
      "type": "종류",
      "breast": "🤱 모유",
      "bottle": "🍼 젖병",
      "side": "쪽",
      "left": "왼쪽",
      "right": "오른쪽",
      "both": "양쪽",
      "durationMinutes": "수유 시간 (분)",
      "amountOz": "양 (oz)",
      "saveFeed": "수유 저장"
    },
    "modalBp": {
      "logBloodPressure": "혈압 기록하기",
      "systolicTop": "수축기 (큰 숫자)",
      "diastolicBottom": "이완기 (작은 숫자)",
      "normalRange": "정상 범위",
      "below12080IsNormal": "120/80 미만이 정상입니다. 임신 중 140/90 이상이면 당일 진료가 필요합니다.",
      "saveReading": "혈압 저장"
    },
    "modalWeight": {
      "logWeight": "체중 기록하기",
      "weightLbs": "체중 (lbs)",
      "weekOfPregnancy": "임신 주차",
      "save": "저장"
    },
    "modalAppt": {
      "addVisit": "진료 추가",
      "visitType": "진료 종류",
      "date": "날짜",
      "questionsToAskBeforehand": "미리 물어볼 질문",
      "notesFromVisit": "진료 메모",
      "saveVisit": "진료 저장"
    },
    "apptType": {
      "selectType": "종류 선택…",
      "obRoutine": "산부인과 – 정기 진료",
      "obTriage": "산부인과 – L&amp;D 분만실 평가 / 예약 없는 진료",
      "mfmConsult": "MFM(모체태아의학) 상담",
      "mfmFollowup": "MFM 추적 진료",
      "endo": "내분비내과",
      "cardio": "심장내과",
      "nephro": "신장내과",
      "ultrasound": "초음파",
      "nst": "비스트레스 검사 (NST)",
      "lactation": "수유 상담",
      "pp2wk": "산후 – 2주",
      "pp6wk": "산후 – 6주",
      "peds25d": "소아과 – 2–5일",
      "peds2wk": "소아과 – 2주",
      "peds2mo": "소아과 – 2개월",
      "family": "가정의학과",
      "other": "기타"
    },
    "install": {
      "addToPhone": "휴대폰에 추가"
    },
    "common": {
      "toolsBack": "도구"
    },
    "nav": {
      "prenatal": "임신 중<br>진료",
      "labor": "진통과<br>분만",
      "recovery": "산후<br>회복",
      "baby": "우리<br>신생아",
      "toolsTrackers": "도구 및<br>기록"
    },
    "tooli18n": {
      "translationHelper": "번역 도우미"
    },
    "usNotice": {
      "title": "미국에서의 진료 안내",
      "body": "이 안내서는 미국에서 제공되는 산전 관리를 설명하며, 미국에서 진료를 받는 산모를 위해 작성되었습니다. 산전 관리는 나라마다 크게 다릅니다. 다른 나라의 진료 일정, 검사, 권고 사항은 여기에 적힌 내용과 다를 수 있습니다. 다른 나라에서 진료를 받고 계신다면 이 앱은 아마 맞지 않을 것입니다.",
      "continue": "이해했습니다"
    },
    "toolimprove": {
      "improveGuide": "이 안내서 개선에 도움 주기"
    },
    "about": {
      "openSource": "자유 오픈소스입니다. 포크하셔도 되지만 자유롭게 유지해 주세요.",
      "viewSource": "소스 코드 보기 (AGPL-3.0)"
    },
    "toolnausea": {
      "nauseaEating": "메스꺼움과 식사"
    }
  },
  "content": {
    "first-trimester": {
      "title": "임신 초기 진료 (4–14주)",
      "sub": "첫 진료에서 예상할 수 있는 것들",
      "body": "<p class=\"lead\">첫 산전 진료는 보통 8–10주경에 하며 가장 오래 걸리는 진료 중 하나입니다. 궁금한 점을 적어 오시고, 파트너가 있다면 함께 오셔도 좋습니다.</p>\n <h4>첫 진료 (8–10주)</h4>\n <ul>\n <li>전체 건강 문진, 신체 검사, 골반 검사, 자궁경부암 검사(시기가 된 경우)</li>\n <li>혈액 검사: 혈액형 및 Rh 인자, CBC(전혈구 검사), 풍진 면역, HIV, B형 간염, 성병 검사</li>\n <li>감염, 단백질, 포도당을 확인하는 소변 검사</li>\n <li>기준 혈압, 체중 측정, 초음파로 출산 예정일 확인</li>\n </ul>\n <div class=\"callout gold\">\n <div class=\"callout-title\">이번 진료에서 물어보세요</div>\n <p>어떤 약과 영양제가 안전한가요? 음식과 여행은 안전한가요? 운동 제한은요? 제게 해당하는 위험 요인은 무엇인가요?</p>\n </div>\n <h4>유전자 선별 검사 (10–13주). 본인 선택</h4>\n <ul>\n <li><strong>NIPT(비침습적 산전 검사, 세포유리 DNA 검사)</strong>. 다운증후군, 18번 삼염색체증, 13번 삼염색체증 등 염색체 이상을 선별하는 혈액 검사입니다. 정확도가 매우 높지만, 진단 검사가 아닌 선별 검사입니다.</li>\n <li><strong>목투명대 초음파</strong>. 아기 목 뒤쪽의 액체 두께를 측정하며, 보통 NIPT와 함께 진행합니다</li>\n <li>선별 검사 결과가 비정상이면 진단 검사(융모막 검사 또는 양수천자)가 제공됩니다</li>\n </ul>\n <p>이 검사들은 <em>선택 사항</em>입니다. 결과를 받았을 때 어떻게 할지 미리 생각해 보세요. 검사가 본인에게 맞는지 의사가 함께 결정을 도와드립니다.</p>\n <div class=\"callout\">\n <div class=\"callout-title\">매 진료마다</div>\n <p>혈압, 체중, 소변을 확인합니다. 아기의 심장 박동은 10–12주경 도플러로 들을 수 있습니다. 새로운 증상, 출혈, 통증이 있으면 꼭 말씀하세요.</p>\n </div>"
    },
    "second-trimester": {
      "title": "임신 중기 진료 (15–27주)",
      "sub": "정밀 초음파, 당부하 검사 등",
      "body": "<p class=\"lead\">진료는 4주에 한 번씩입니다. 18–20주의 정밀 초음파는 중요한 이정표입니다. 출산 전 아기를 가장 자세히 살펴보는 검사입니다.</p>\n <h4>정밀 초음파 (18–20주)</h4>\n <ul>\n <li>아기의 뇌, 심장, 척추, 신장, 팔다리, 얼굴을 자세히 검사합니다</li>\n <li>태반 위치 확인. 태반이 낮게 위치한 경우(전치태반 가능성) 중요합니다</li>\n <li>자궁경부 길이 측정. 자궁경부가 짧으면 조산 위험이 높아집니다</li>\n <li>양수량을 추정합니다</li>\n <li>원하는 경우 많은 가족이 이때 아기의 성별을 알게 됩니다</li>\n </ul>\n <div class=\"callout gold\">\n <div class=\"callout-title\">이번 진료에서 물어보세요</div>\n <p>제 태반은 어디에 있나요? 자궁경부 길이는 어떤가요? 아기 성장은 순조로운가요? 추가 확인이 필요한 소견이 있나요?</p>\n </div>\n <h4>선택적 쿼드 검사 / AFP (15–20주)</h4>\n <p>신경관 결손과 염색체 이상을 선별하는 혈액 검사입니다. 이미 NIPT를 받았다면 이 검사가 필요한지 의사에게 물어보세요.</p>\n <h4>당부하 검사 (24–28주)</h4>\n <ul>\n <li>임신성 당뇨를 선별하는 검사입니다. 당분이 든 음료를 마시고 1시간 후에 채혈합니다</li>\n <li>결과가 높게 나오면(「불합격」이 아니라 선별 검사일 뿐입니다) 3시간짜리 확진 검사를 받습니다</li>\n <li>임신성 당뇨는 관리할 수 있습니다. 식이 조절, 운동, 필요시 약물로 관리합니다</li>\n </ul>\n <div class=\"callout\">\n <div class=\"callout-title\">이제 생각해 보세요</div>\n <p>출산 교실, 출산 계획, 모유 수유 계획, 소아과 의사 선택, 휴가 계획, 아기 용품 준비.</p>\n </div>"
    },
    "third-trimester": {
      "title": "임신 후기 진료 (28–40주 이상)",
      "sub": "매주 진료, GBS 검사, 자궁경부 검사",
      "body": "<p class=\"lead\">28주 이후에는 2주에 한 번, 36주 이후에는 매주 진료를 받습니다. 결승선이 눈앞에 있습니다.</p>\n <h4>28주. Rh 인자 및 Tdap</h4>\n <ul>\n <li><strong>RhoGAM 주사</strong>. Rh 음성인 경우에 맞습니다. 면역 체계가 미래의 Rh 양성 아기를 공격하는 것을 예방합니다</li>\n <li><strong>Tdap 백신</strong>(백일해 추가 접종). 27–36주에 접종을 강력히 권장합니다. 항체가 태반을 통해 아기에게 전달되어, 아기가 접종받을 수 있기 전까지 신생아를 보호합니다</li>\n </ul>\n <h4>35–37주. B군 연쇄상구균(GBS) 검사</h4>\n <p>질과 직장을 간단히 면봉으로 채취하는 검사입니다. 여성의 약 25%가 정상적으로 GBS를 보유하고 있으며, 성병이 아니고 산모에게 해롭지도 않습니다. 양성이면 분만 중 정맥 항생제를 투여하여 출산 중 아기가 감염되지 않도록 보호합니다.</p>\n <h4>36–40주. 자궁경부 검사 및 아기 위치 확인</h4>\n <ul>\n <li>의사가 자궁경부 검사를 제안할 수 있습니다. 자궁경부가 얼마나 열렸고 얇아졌는지 확인합니다</li>\n <li>아기의 위치를 확인합니다(머리가 아래로 향한 것이 이상적입니다)</li>\n <li>유도 분만 계획을 논의합니다: ACOG(미국 산부인과 학회)는 42주까지 분만할 것을 권장하며, 많은 의사가 39주에 선택적 유도 분만을 제안합니다</li>\n </ul>\n <div class=\"callout\">\n <div class=\"callout-title\">36주 이후 물어보세요</div>\n <p>언제 유도 분만을 권장하시나요? 예정일이 지나면 어떤 계획인가요? 언제 병원에 가야 하나요?</p>\n </div>"
    },
    "sve": {
      "title": "자궁경부 검사(SVE) 설명",
      "sub": "개대, 소실, 아기 머리 위치",
      "body": "\n        <p class=\"lead\">SVE는 멸균 질 내진(Sterile Vaginal Exam)의 약자입니다. 자궁경부가 분만을 준비하고 있는지, 또는 분만이 진행되고 있는지 의사가 확인하는 방법입니다.</p>\n        <p>의사가 장갑을 낀 두 손가락으로 자궁경부를 만져서 세 가지를 평가합니다:</p>\n        <table class=\"data-table\">\n          <tr><th>확인하는 것</th><th>의미</th></tr>\n          <tr><td><strong>개대(Dilation)</strong><br>0–10 cm</td><td>자궁경부가 얼마나 열렸는지. 10 cm = 완전히 열림, 힘을 줄 준비 완료.</td></tr>\n          <tr><td><strong>소실(Effacement)</strong><br>0–100%</td><td>자궁경부가 얼마나 얇아졌는지. 100% = 완전히 얇아짐.</td></tr>\n          <tr><td><strong>위치(Station)</strong><br>-5에서 +5</td><td>아기 머리가 얼마나 내려왔는지. 0 = 좌골극 높이(중간 지점). +3에서 +5 = 거의 나옴.</td></tr>\n        </table>\n        <div class=\"callout\">\n          <div class=\"callout-title\">비숍 점수(Bishop Score)</div>\n          <p>의료진은 개대, 소실, 위치, 자궁경부의 질감, 방향을 합산한 점수(비숍 점수)를 사용하여 자궁경부가 분만에 얼마나 준비되었는지 예측하기도 합니다. 점수가 8점 이상이면 자궁경부 상태가 좋고 유도 분만 성공 가능성이 높음을 의미합니다.</p>\n        </div>\n        <p>임신 후기의 SVE는 선택 사항입니다. 36–38주의 자궁경부 개대 정도가 분만 시작 시기를 정확히 예측하지는 못합니다. 활동성 분만 중에는 2–4시간마다 SVE를 하여 10 cm까지의 진행 상황을 추적합니다.</p>"
    },
    "exercise-pregnancy": {
      "title": "임신 중 운동",
      "sub": "이점, 안전한 활동, 피해야 할 것",
      "body": "<p class=\"lead\">규칙적인 중등도 운동은 대부분의 임산부에게 안전하고 유익합니다. ACOG(미국 산부인과 학회)는 주당 150분의 중등도 활동을 권장합니다.</p>\n <h4>이점</h4>\n <ul>\n <li>허리 통증, 부종, 변비, 피로를 줄여줍니다</li>\n <li>임신성 당뇨, 자간전증, 과도한 체중 증가의 위험을 낮춥니다</li>\n <li>수면, 기분, 활력을 개선합니다</li>\n <li>분만 시간이 짧아지고 회복이 빨라지는 경우가 많습니다</li>\n <li>활동적인 산모의 아기는 심박수 패턴이 더 건강한 경우가 많습니다</li>\n </ul>\n <h4>어느 시기든 좋은 선택</h4>\n <ul>\n <li><strong>걷기</strong>. 가장 쉽고 안전하며 어떤 체력 수준에서도 가능합니다</li>\n <li><strong>수영 및 수중 에어로빅</strong>. 임신 후기에 특히 좋습니다. 관절의 부담을 덜어줍니다</li>\n <li><strong>산전 요가 또는 필라테스</strong>. 코어와 골반저 근력을 키우고 허리 통증을 줄여줍니다</li>\n <li><strong>고정식 자전거</strong>. 넘어질 위험이 낮고 좋은 유산소 운동입니다</li>\n <li><strong>수정된 근력 운동</strong>. 가볍거나 중간 정도의 무게로 합니다. 숨을 참는 것(발살바 호흡)은 피하세요</li>\n <li><strong>케겔 운동</strong>. 골반저 근육을 수축했다 이완합니다. 10회씩 3세트를 매일 하세요</li>\n </ul>\n <h4>임신 초기 이후 피해야 할 것</h4>\n <ul>\n <li>똑바로 누워서 하는 운동(대정맥을 압박합니다)</li>\n <li>접촉 스포츠 또는 넘어지거나 부딪힐 위험이 있는 활동</li>\n <li>스쿠버 다이빙(아기에게 감압 위험이 있습니다)</li>\n <li>핫요가 또는 극심한 더위 속에서의 운동</li>\n <li>고도에 적응하지 않은 상태에서의 고지대 활동</li>\n </ul>\n <div class=\"callout\">\n <div class=\"callout-title\">말하기 테스트</div>\n <p>운동하면서 대화를 이어갈 수 있어야 합니다. 숨이 차서 말하기 어렵다면? 속도를 줄이세요. 운동 강도를 안전한 범위로 유지하는 간단한 기준입니다.</p>\n </div>\n <div class=\"callout alert\">\n <div class=\"callout-title\">다음 증상이 있으면 멈추고 의료진에게 연락하세요</div>\n <p>질 출혈, 어지러움, 흉통, 심한 호흡 곤란, 진통, 양수 누출, 태동 감소, 종아리 통증 및 부종.</p>\n </div>"
    },
    "signs-of-labor": {
      "title": "분만 징후: 언제 병원에 갈까",
      "sub": "진진통 vs 브랙스턴 힉스, 그리고 5-1-1 규칙",
      "body": "<p class=\"lead gold\">진짜 진통과 가짜 진통을 구별하면 불필요한 병원 방문을 많이 줄일 수 있습니다. 구별 방법을 알려드립니다.</p>\n <table class=\"data-table\">\n <tr><th>진진통</th><th>브랙스턴 힉스(가진통)</th></tr>\n <tr><td>점점 길어지고, 강해지고, 간격이 좁아짐</td><td>불규칙하고, 시간이 지나도 심해지지 않음</td></tr>\n <tr><td>쉬거나 움직여도 멈추지 않음</td><td>자세를 바꾸거나 수분을 섭취하면 멈추는 경우가 많음</td></tr>\n <tr><td>통증이 주로 허리에서 시작해 앞쪽으로 퍼짐</td><td>주로 앞쪽에서만 느껴짐</td></tr>\n <tr><td>자궁경부가 변화함</td><td>자궁경부 변화 없음</td></tr>\n </table>\n <div class=\"callout gold\">\n <div class=\"callout-title\">5-1-1 규칙 (첫 아기)</div>\n <p>진통이 <strong>5분 간격으로, 1분씩 지속되고, 최소 1시간 이어지면</strong> 병원으로 가세요. 둘째 이후 아기라면 더 일찍 가세요. 진통이 6–8분 간격일 때 연락하세요. 분만이 더 빨리 진행됩니다.</p>\n </div>\n <div class=\"callout alert\">\n <div class=\"callout-title\">다음 중 하나라도 있으면 즉시 병원으로</div>\n <p><strong>양수 파수</strong>(쏟아지거나 계속 샘) · 선홍색 출혈(점상 출혈 이상) · 태동이 멈춤 · 지속적인 심한 복통 · 자간전증 징후: 타이레놀로도 낫지 않는 심한 두통, 시야 변화, 갑작스러운 심한 부종</p>\n </div>\n <h4>집에서 보내는 초기 진통</h4>\n <p>진통이 가볍고 불규칙하다면 초기 진통은 오히려 집이 더 편안합니다. 따뜻한 샤워, 걷기, 휴식, 수분 섭취, 먹을 수 있을 때 가벼운 간식을 시도해 보세요.</p>"
    },
    "what-happens-on-arrival": {
      "title": "분만실(L&D)에 도착하면 일어나는 일",
      "sub": "분류 평가, 입원, 그리고 자리 잡기",
      "body": "<p class=\"lead gold\">분만실에 입원하기 전에 먼저 분류실(triage)에서 평가를 받게 됩니다. 이 과정은 산모님과 아기가 안정적인지, 그리고 진정한 활동기 진통인지 확인하기 위한 것입니다.</p>\n <h4>1단계: 분류 평가</h4>\n <ul>\n <li>자궁경부 개대와 소실 정도를 확인하는 질 내진(SVE)</li>\n <li>외부 태아 모니터 부착. 배에 두 개의 띠를 두르고, 하나는 자궁 수축을, 다른 하나는 아기의 심박수를 추적합니다</li>\n <li>혈압, 체온, 맥박, 산소 포화도 확인</li>\n <li>정맥 주사(IV) 확보 (팔에 작은 카테터를 놓는 표준 절차)</li>\n <li>소변 검체 채취</li>\n <li>산전 기록에서 GBS(B군 연쇄상구균) 상태 확인</li>\n </ul>\n <h4>2단계: 입원 또는 대기 요청</h4>\n <p>자궁경부가 4–6 cm 미만으로 열린 경우(병원과 상황에 따라 다름), 집으로 돌아가거나 1–2시간 정도 걸은 후 다시 검사를 받으라는 안내를 받을 수 있습니다. 이것은 거절이 아닙니다. 초기 진통은 집에서 지내는 편이 실제로 더 안전하고 편안합니다. 낙심하지 마세요.</p>\n <h4>3단계: 분만실</h4>\n <p>입원이 결정되면 출산까지 그 방에 머물게 됩니다. 담당 간호사가 산모님의 주된 안내자가 되어 정기적으로 상태를 확인합니다. 이때 출산에 대한 희망 사항과 통증 관리 방법을 상의하세요.</p>\n <div class=\"callout gold\">\n <div class=\"callout-title\">병원에 가져갈 것</div>\n <p>신분증과 보험 카드 · 연락처가 적힌 이 책자 · 휴대폰 충전기 · 진통 및 회복 기간에 입을 편안한 옷 · 아기의 퇴원용 옷과 카시트 · 세멘도구 · 동반 보호자를 위한 간식</p>\n </div>"
    },
    "stages-of-labor": {
      "title": "분만의 단계",
      "sub": "몸에서 일어나는 일과 걸리는 시간",
      "body": "<table class=\"data-table\">\n <tr><th class=\"gold\">단계</th><th class=\"gold\">일어나는 일</th><th class=\"gold\">일반적인 소요 시간</th></tr>\n <tr><td><strong>1기 잠재기</strong><br>0–6 cm</td><td>자궁경부가 열리고 수축이 시작됨. 심한 생리통이나 허리 통증처럼 느껴질 수 있음</td><td>몇 시간에서 아주 오래; 개인차가 큼</td></tr>\n <tr><td><strong>1기 활동기</strong><br>6–10 cm</td><td>수축이 강해짐. 3–5분 간격으로 45–60초간 지속. 대부분의 산모가 이때 통증 관리를 사용</td><td>첫아기는 1–8시간; 둘째 이후는 더 빠름</td></tr>\n <tr><td><strong>1기 이행기</strong><br>8–10 cm</td><td>가장 격렬한 시기. 2–3분 간격의 수축. 짧지만 가장 힘든 단계. 아기가 아래로 낮아짐</td><td>15–60분</td></tr>\n <tr><td><strong>2기 힘주기</strong><br>10 cm</td><td>자궁경부가 완전히 열림. 힘을 줄 시간. 강한 배변감 같은 느낌. 아기의 머리가 보이기 시작함</td><td>20분–3시간 (첫아기)</td></tr>\n <tr><td><strong>3기 태반</strong></td><td>아기가 나온 후 태반이 배출됨. 자궁 수축을 돕기 위해 피토신(Pitocin, 옥시토신)을 받을 수 있음</td><td>5–30분</td></tr>\n </table>\n <div class=\"callout gold\">\n <div class=\"callout-title\">분만 유도</div>\n <p>자궁경부에 도움이 필요한 경우, 의사가 약물(미소프로스톨, 옥시토신/피토신)이나 풍선 카테터를 사용해 자궁경부를 부드럽게 하고 열리게 할 수 있습니다. 분만 유도는 12–24시간 이상 걸릴 수 있으며, 특히 첫아기이고 자궁경부가 준비되지 않은 경우 더 오래 걸립니다. 시간이 걸릴 것을 염두에 두세요.</p>\n </div>\n <h4>태아 모니터링</h4>\n <p>대부분의 병원은 활동기 진통 동안 지속적인 전자 태아 모니터링을 사용합니다. 이는 수축과 연관된 아기의 심박수 패턴을 추적하여 태아 곤란증의 징후를 조기에 발견하는 데 도움이 됩니다. 걷거나 욕조를 사용하고 싶다면 무선(원격측정) 모니터가 있는지 문의하세요.</p>"
    },
    "pain-management": {
      "title": "통증 관리: 모든 선택지",
      "sub": "무약물 방법부터 경막외 마취까지",
      "body": "<p class=\"lead gold\">분만 통증을 다루는 단 하나의 정답은 없습니다. 목표는 건강한 아기와 스스로 만족할 수 있는 출산 경험이지, 특정한 방법이 아닙니다.</p>\n <h4>약물을 쓰지 않는 방법</h4>\n <ul>\n <li><strong>수치료</strong>. 샤워나 욕조에서 진통을 겪는 것은 많은 산모의 통증을 크게 줄여 줍니다. 가장 효과적인 무약물 방법 중 하나</li>\n <li><strong>움직임 &amp; 자세</strong>. 걷기, 흔들기, 네발 자세, 분만 볼, 옆으로 눕기 모두 수축의 느낌을 바꿔 줍니다</li>\n <li><strong>호흡법</strong>. 느리고 일정한 호흡은 가장 효과적인 도구 중 하나입니다. 출산 준비 교실에서 잘 배울 수 있습니다</li>\n <li><strong>압박</strong>. 수축 중 천골(허리 아래쪽)을 강하게 눌러 주면 허리 통증형 진통이 크게 줄어듭니다</li>\n <li><strong>TENS 기기</strong>. 허리 아래쪽에 작은 전기 자극을 주어 통증 신호를 방해합니다. 초기 진통에 가장 도움이 됩니다</li>\n <li><strong>온열 &amp; 냉찜질</strong>. 허리 아래쪽에는 온찜질 팩, 이마에는 냉찜질</li>\n </ul>\n <h4>아산화질소 (웃음가스)</h4>\n <p>수축 중에 <em>산모님이 직접</em> 들고 조절하는 마스크를 통해 흡입합니다. 통증을 완전히 없애지는 않지만 날카로운 정도를 누그러뜨립니다. 5분 안에 효과가 사라집니다. 일부 산모에게 어지럼이나 메스꺼움을 유발할 수 있습니다. 미국의 많은 병원에서 제공됩니다. 산모님의 병원에서 제공하는지 문의하세요.</p>\n <h4>정맥/근육 주사 아편계 진통제</h4>\n <p>펜타닐이나 모르핀 같은 약물을 정맥 주사로 투여하면 통증은 누그러지지만 완전히 없어지지는 않습니다. 졸음, 메스꺼움, 가려움을 유발할 수 있습니다. 소량이 아기에게 전달됩니다. 타이밍이 중요합니다(분만 직전에는 피해 아기가 깨어 있는 상태로 태어나도록 합니다).</p>\n <div class=\"callout gold\">\n <div class=\"callout-title\">마음을 바꿔도 됩니다</div>\n <p>무약물로 시작했다가 나중에 경막외 마취를 요청하는 것은 완전히 정상적이고 타당합니다. 반대로 경막외 마취를 계획했다가 진행이 빨라 시간이 없는 경우도 흔합니다. 유연하게 대처하세요.</p>\n </div>"
    },
    "epidural": {
      "title": "경막외 마취: 알아둘 것",
      "sub": "원리, 위험, 그리고 사실과 오해",
      "body": "<p class=\"lead gold\">경막외 마취는 가장 효과적인 분만 진통 방법입니다. 미국 병원에서 분만하는 산모의 약 75%가 사용합니다.</p>\n <h4>원리</h4>\n <p>마취과 의사가 허리 아래쪽의 경막외 공간에 작고 유연한 카테터(가는 관)를 놓습니다. 척수 자체에 들어가는 것은 아닙니다. 국소마취제와/또는 아편계 약물이 카테터를 통해 흘러 자궁에서 오는 통증 신호를 전달하는 신경을 마비시킵니다. 산모님은 완전히 깨어 있고, 보통 압박감을 느끼고 다리를 움직일 수 있습니다.</p>\n <h4>예상되는 과정</h4>\n <ul>\n <li>시술에는 10–15분이 걸리며, 수축 중에도 움직이지 않고 있어야 합니다</li>\n <li>15–20분 후 완전한 효과가 나타납니다</li>\n <li>지속적인 태아 모니터링과 정맥 주사가 필요합니다</li>\n <li>혈압을 자주 확인합니다. 일시적인 혈압 저하는 흔하며 수액이나 약물로 쉽게 관리됩니다</li>\n <li>힘을 주고 싶은 느낌이 줄어들 수 있습니다. 간호사가 힘주는 것을 안내해 줍니다</li>\n <li>마비가 된 후에는 보통 도뇨관을 삽입합니다</li>\n </ul>\n <h4>실제 위험 (드묾)</h4>\n <ul>\n <li><strong>척수액 누출 두통</strong> (~1%): 작은 경막 천공으로 발생합니다. \"혈액 패치\"로 치료 가능합니다</li>\n <li><strong>일시적 저혈압</strong>: 매우 흔하며 관리가 쉽습니다</li>\n <li><strong>불완전한 진통 효과</strong>: 드물게 위치 조정이나 재시술이 필요합니다</li>\n <li><strong>가려움</strong>: 아편계 성분 때문에 생기며 보통 가볍습니다</li>\n <li><strong>발열</strong>: 경막외 마취와 관련된 발열은 실제로 있지만 대개 해롭지 않고 관리됩니다</li>\n </ul>\n <div class=\"callout\">\n <div class=\"callout-title\">핵심 사실. 제왕절개 오해</div>\n <p>경막외 마취는 제왕절개율을 높이지 <strong>않습니다</strong>. 이것은 산과학에서 가장 흔하고 가장 많이 연구된 오해 중 하나입니다. 여러 대규모 무작위 시험이 이를 확인했습니다. 활동기 진통 중에는 언제든 경막외 마취를 요청할 수 있습니다.</p>\n </div>"
    },
    "csection": {
      "title": "제왕절개: 이유와 예상되는 과정",
      "sub": "예정 수술과 비예정 수술, 수술 과정, 회복",
      "body": "<p class=\"lead gold\">제왕절개는 복부와 자궁을 절개해 아기를 꺼내는 수술 분만입니다. 미국 출산의 약 30%가 제왕절개입니다.</p>\n <h4>예정된 (계획된) 이유</h4>\n <ul>\n <li>전치태반. 태반이 자궁경부 입구를 덮고 있는 경우</li>\n <li>아기가 둔위(발이 아래) 또는 횡위(옆으로 누운 자세)이고 돌아오지 않은 경우</li>\n <li>이전에 고전적(세로) 자궁 절개를 받은 경우</li>\n <li>특정 자세의 쌍둥이 또는 그 이상의 다태아</li>\n <li>특정 산모 질환 (중증 심장병, 활동성 생식기 헤르페스 발진)</li>\n </ul>\n <h4>진통 중 예상치 못한 이유</h4>\n <ul>\n <li>태아 심박수 이상 (아기가 곤란 징후를 보이는 경우)</li>\n <li>분만 정지. 충분한 수축과 시간에도 진행이 없는 경우</li>\n <li>태반 조기박리. 태반이 일찍 떨어지는 경우</li>\n <li>제대 탈출. 탯줄이 아기보다 먼저 자궁경부를 통해 나오는 경우</li>\n </ul>\n <h4>수술실에서</h4>\n <ul>\n <li>척추 또는 경막외 마취. 산모님은 깨어 있고 가슴 아래가 마비됩니다</li>\n <li>수술 부위를 가리는 막이 설치됩니다. 출산 순간에 낮춰 달라고 요청할 수 있습니다</li>\n <li>보통 동반 보호자가 함께 있을 수 있습니다</li>\n <li>압박감과 당기는 느낌은 있지만 통증은 없습니다</li>\n <li>수술실에서도 아기를 바로 가슴에 올려 주는 경우가 많습니다 (\"부드러운 제왕절개\")</li>\n <li>총 소요 시간: 약 45–60분; 출산 자체는 5–10분</li>\n </ul>\n <h4>제왕절개 후 회복</h4>\n <ul>\n <li>입원 기간: 2–4일 (질 분만 후 1–2일과 비교)</li>\n <li>통증은 정해진 일정의 이부프로펜 + 아세트아미노펜 ± 단기 아편계 진통제로 관리합니다</li>\n <li>당일부터 걷기 시작합니다. 혈전 예방에 매우 중요합니다</li>\n <li>4–6주 동안 아기보다 무거운 것은 들지 않습니다</li>\n <li>절개 부위는 가로 방향의 \"비키니 라인\" 흉터로, 스테이플 또는 흡수성 봉합사로 닫습니다</li>\n </ul>\n <div class=\"callout alert\">\n <div class=\"callout-title\">제왕절개 퇴원 후 이런 경우 연락하세요</div>\n <p>절개 부위가 벌어지거나, 발적이 바깥으로 번지거나, 이상한 분비물이 나오는 경우 · 열이 &gt;100.4°F인 경우 · 통증이 나아지기는커녕 심해지는 경우 · 1시간 만에 패드가 흠뻑 젖는 경우</p>\n </div>\n <div class=\"callout gold\">\n <div class=\"callout-title\">VBAC. 제왕절개 후 질 분만</div>\n <p>이전에 하부 횡절개 제왕절개를 한 번 받은 경우, 이번 임신에 VBAC(제왕절개 후 질 분만)이 가능할 수 있습니다. 성공률은 60–80%입니다. 산전 관리 초기에 상의하세요.</p>\n </div>"
    },
    "mfm": {
      "title": "고위험 임신과 MFM 의뢰",
      "sub": "MFM이란 무엇이며 왜 의뢰될 수 있는가",
      "body": "<p class=\"lead gold\">MFM은 모체태아의학(Maternal-Fetal Medicine)의 약자로, 고위험 임신을 전문으로 하는 산부인과 세부전문의입니다. 의뢰는 전문가의 관리를 받게 된다는 뜻이지, 불안해할 일이 아닙니다.</p>\n <h4>MFM 의뢰의 흔한 이유</h4>\n <ul>\n <li>자간전증 또는 만성 고혈압</li>\n <li>임신 전 당뇨(1형 또는 2형) 또는 인슐린이 필요한 임신성 당뇨</li>\n <li>쌍둥이, 세쌍둥이 또는 그 이상의 다태아</li>\n <li>조산(37주 이전 분만) 병력</li>\n <li>초음파에서 발견된 짧은 자궁경부 (자궁경부 묠력증)</li>\n <li>정밀 초음파에서 발견된 태아 성장 제한 또는 구조적 이상</li>\n <li>자가면역 질환: 루푸스, 항인지질증후군</li>\n <li>만성 신장 질환, 심장 질환, 혈액 응고 장애</li>\n <li>추가 검사가 필요한 유전자 선별검사 이상 결과</li>\n <li>합병증이 있는 고령 임신 (&gt;35세)</li>\n </ul>\n <h4>MFM이 실제로 하는 일</h4>\n <ul>\n <li>전문 초음파 시행. 정밀 태아 구조 검사, 태아 심장 초음파, 연속 성장 초음파</li>\n <li>약물, 분만 시기, 분만 방식에 대한 자문</li>\n <li>산부인과 의사나 조산사와 함께 관리하거나, 복잡한 경우 주치의 역할을 맡을 수 있습니다</li>\n <li>대부분의 산모는 여전히 원래 담당 의료진과 분만합니다</li>\n </ul>\n <div class=\"callout\">\n <div class=\"callout-title\">MFM 의사에게 물어볼 것</div>\n <p>구체적인 우려 사항은 무엇인가요? 어떻게 관찰하나요? 분만 방법이나 시기가 달라지나요? 진료나 초음파를 더 자주 받아야 하나요?</p>\n </div>"
    },
    "immediate-postpartum": {
      "title": "분만 후 첫 몇 시간",
      "sub": "\"제4기\". 무엇을 모니터링하는지",
      "body": "<p class=\"lead rose\">출산 후 첫 2시간, \"분만 제4기\"라고 부릅니다, 은 모니터링이 가장 중요한 시기입니다. 간호사가 산모님을 자주 확인할 것입니다.</p>\n <h4>무엇을 모니터링하나요</h4>\n <ul>\n <li><strong>자궁</strong>. 간호사가 자궁이 단단하고 잘 수축되어 있는지 확인하여 출혈을 예방합니다. 주기적으로 배를 눌러 확인합니다.</li>\n <li><strong>출혈(오로)</strong>. 양과 색깔을 기록합니다</li>\n <li><strong>혈압과 심박수</strong></li>\n <li><strong>회음부 또는 절개 부위</strong></li>\n <li><strong>통증 정도</strong>. 통증이 심해질 때까지 기다리지 마세요. 미리 진통제를 요청하세요</li>\n </ul>\n <h4>피부 맞대기(스킨투스킨)</h4>\n <p>출산 직후, 제왕절개 후에도, 아기를 산모의 맨가슴에 올려놓으면 아기의 체온, 혈당, 호흡이 조절되고 심박수가 안정되며, 유대감 형성과 모유 수유 시작을 크게 촉진합니다. 특별한 의학적 이유가 없다면 이것이 이루어지도록 요청하세요.</p>\n <div class=\"callout rose\">\n <div class=\"callout-title\">지연 제대 결찰</div>\n <p>제대를 결찰하고 자르기 전에 30~60초(또는 그 이상) 기다리면 철분이 풍부한 혈액 80~100 mL가 아기에게 추가로 전달됩니다. 이는 현재 대부분의 미국 병원에서 표준 진료입니다. 미리 계획되어 있는지 확인할 수 있습니다.</p>\n </div>\n <h4>첫 식사</h4>\n <p>자연분만 후에는 보통 분만 직후부터 식사할 수 있습니다. 제왕절개 후에는 먼저 맑은 유동식부터 시작하고, 견딜 수 있으면 일반식으로 넘어갑니다. 보통 몇 시간 이내입니다.</p>"
    },
    "physical-recovery": {
      "title": "신체 회복: 예상되는 것들",
      "sub": "오로, 회음부 관리, 통증 관리",
      "body": "<h4>산후 출혈(오로)</h4>\n <p>오로는 자궁 내막이 벗겨지고 태반이 붙어 있던 자리가 아물면서 나오는 정상적인 분비물입니다. 시간이 지나면서 변합니다:</p>\n <table class=\"data-table\">\n <tr><th class=\"rose\">일수</th><th class=\"rose\">모양</th><th class=\"rose\">정상?</th></tr>\n <tr><td>1–4</td><td>선홍색, 생리량이 많을 때와 비슷</td><td>✓ 예</td></tr>\n <tr><td>5–10</td><td>분홍색~갈색, 양이 줄어듦</td><td>✓ 예</td></tr>\n <tr><td>10–28+</td><td>노란빛 흰색, 매우 적은 양</td><td>✓ 예</td></tr>\n </table>\n <div class=\"callout alert\">\n <div class=\"callout-title\">다음의 경우 담당 의료진에게 연락하세요</div>\n <p>2시간 연속으로 한 시간에 생리대 1개 이상을 적시는 경우 · 골프공 크기의 응혈이 나오는 경우 · 옅어졌던 선홍색 출혈이 다시 시작되는 경우 · 악취가 나는 분비물</p>\n </div>\n <h4>회음부 관리(자연분만 후)</h4>\n <ul>\n <li>화장실에 다녀올 때마다 미지근한 물이 든 회음부 세정병(페리 보틀)을 사용하세요. 앞에서 뒤로</li>\n <li>처음 24시간은 얼음찜질, 이후에는 따뜻한 좌욕으로 바꾸세요(10~15분, 하루 2~3회)</li>\n <li>위치하젤 패드(예: Tucks)가 부기와 치질을 진정시킵니다</li>\n <li><strong>변비약(도큐세이트/콜레이스)</strong>. 즉시 시작하세요. 회음부 봉합 상태에서의 변비는 매우 불편하고, 힘을 주면 봉합 부위가 터질 위험이 있습니다</li>\n </ul>\n <h4>통증 관리</h4>\n <p>이부프로펜(6시간마다 600 mg)과 아세트아미노펜(6시간마다 650 mg)을 일정에 맞춰 번갈아 복용하는 것이 통증이 심해질 때까지 기다리는 것보다 훨씬 효과적입니다. 1일차에 간호사에게 복용 일정을 글로 적어달라고 요청하고 그대로 지키세요.</p>"
    },
    "mood-ppd": {
      "title": "기분과 정서적 회복",
      "sub": "산후 우울감, 산후 우울증, 도움을 요청해야 할 때",
      "body": "<p class=\"lead rose\">분만 후 극적인 호르몬 변화는 기분에 큰 영향을 줍니다. 감정의 변화는 예상되는 일이지만, 일부 증상은 주의가 필요합니다.</p>\n <h4>산후 우울감(정상. 산모의 최대 80%)</h4>\n <p>출산 후 첫 주에 에스트로겐과 프로게스테론이 급격히 떨어지면서 눈물이 나고, 기분이 오락가락하고, 불안하고, 짜증이 날 수 있습니다. 산후 우울감은 보통 2주 이내에 저절로 사라집니다.</p>\n <h4>산후 우울증(PPD). 산모 8명 중 1명</h4>\n <p>PPD(산후 우울증)는 의학적 질환입니다. 치료 가능한 기분 장애이지, 성격의 결함이나 나쁜 엄마라는 신호가 아닙니다.</p>\n <div class=\"callout rose\">\n <div class=\"callout-title\">PPD의 증상</div>\n <p>지속적인 슬픔이나 공허함 · 아기와 유대감을 형성하기 어려움 · 자신이 나쁜 엄마라거나 아기가 자기 없는 편이 낫겠다는 느낌 · 심한 불안이나 공황 발작 · 아기가 자는데도 잠들지 못함 · 예전에 즐기던 것에 대한 흥미 상실 · 자신이나 아기를 해치고 싶은 생각</p>\n </div>\n <p>이러한 증상이 2주 이상 지속되거나 어느 시점에서든 심하다면 의료진에게 알리세요. PPD는 상담 치료, 지지 모임, 약물(대부분 모유 수유 중에도 안전)로 효과적으로 치료됩니다. <strong>6주 검진까지 기다리지 말고 말씀하세요.</strong></p>\n <div class=\"callout alert\">\n <div class=\"callout-title\">산후 정신병. 드물지만 의료 응급 상황</div>\n <p>출산 후 며칠 내에 나타나는 환각, 망상, 극심한 혼란 또는 초조함. 즉시 911에 전화하거나 응급실로 가세요. 드물지만(1,000명 중 1~2명) 긴급한 치료가 필요합니다.</p>\n </div>\n <h4>산후 불안</h4>\n <p>덜 알려져 있지만 매우 흔합니다. 아기의 안전에 대한 과도하고 침투적인 걱정, 지칠 정도로 피곤한데도 잠들기 어려움, 계속 확인하는 행동, 심장이 빨리 뛰는 등의 신체 증상. 이 역시 매우 잘 치료됩니다. 의사에게 말씀하세요.</p>"
    },
    "pelvic-rest": {
      "title": "골반 휴식과 성관계 재개",
      "sub": "6주 권고가 있는 이유",
      "body": "<p class=\"lead rose\">ACOG(미국 산부인과학회)는 분만 후 최소 6주가 지날 때까지 질 성관계를 기다릴 것을 권장합니다. 이 지침이 있는 이유를 설명합니다.</p>\n <h4>왜 6주인가요?</h4>\n <ul>\n <li>자궁이 완전히 수축하고 태반이 붙어 있던 자리가 완전히 아무는 데 4~6주가 필요합니다</li>\n <li>질 열상, 찢어짐 또는 회음절개 봉합 부위가 아물 시간이 필요합니다</li>\n <li>제왕절개 절개 부위, 겉으로 보이는 흉터와 자궁 내부의 절개 부위 모두, 최소 6주가 필요합니다</li>\n <li>10 cm까지 열였던 자궁경부는 몇 주에 걸쳐 서서히 닫힙니다. 이 기간에는 감염이 자궁까지 도달하는 직접적인 통로가 됩니다</li>\n </ul>\n <h4>\"골반 휴식\"의 의미</h4>\n <p>질 안에 아무것도 넣지 않습니다: 성관계, 탐폰, 생리컵, 질 세척 모두 금지. 회복 기간 동안 오로에는 생리대만 사용하세요.</p>\n <div class=\"callout rose\">\n <div class=\"callout-title\">재개할 준비가 되었을 때</div>\n <p><strong>건조함은 매우 흔합니다</strong>. 특히 모유 수유 중에는 에스트로겐이 낮게 유지되기 때문입니다. 수성 윤활제를 사용하세요. 천천히 하세요. 처음에 약간의 불편함은 정상입니다. 지속적인 통증은 정상이 아닙니다. 의사에게 말씀하세요. <strong>피임을 하세요</strong>. 생리가 돌아오기 전에도 임신할 수 있습니다. 6주 검진에서 피임 방법을 상담하세요.</p>\n </div>\n <div class=\"callout gold\">\n <div class=\"callout-title\">분만 후 피임</div>\n <p>모유 수유 중에도, 생리가 돌아오기 전에도, 산후 이르게는 3주부터 배란과 임신이 가능합니다. 바로 임신을 원하지 않는다면 퇴원 전에, 늦어도 2주 검진에서 피임에 대해 상담하세요.</p>\n </div>"
    },
    "postpartum-exercise": {
      "title": "분만 후 운동 재개",
      "sub": "언제 무엇이 안전한지, 골반저 물리치료",
      "body": "<p class=\"lead rose\">분만 후 다시 활동하는 것은 기분, 활력, 신체 회복을 좋게 합니다. 하지만 시기가 중요합니다.</p>\n <h4>바로 시작(1~2일차)</h4>\n <ul>\n <li><strong>케겔 운동</strong>. 편하다면 24~48시간 이내에 시작하세요. 회복을 빠르게 하고, 요실금 위험을 줄이며, 골반저 근육의 긴장도를 회복합니다. 5~10초씩 유지하는 동작 10회를 한 세트로, 하루에 여러 번 3세트씩 하세요.</li>\n <li><strong>가벼운 걷기</strong>. 1~2일차부터 짧은 산책을 권장합니다. 몸이 준비되는 대로 늘려가세요.</li>\n <li><strong>깊은 복식 호흡</strong>. 숨을 들이마시며 배를 부풀리고, 천천히 내쉬세요. 깊은 코어 근육과 다시 연결되는 데 도움이 됩니다.</li>\n </ul>\n <h4>2~6주차</h4>\n <ul>\n <li>걷는 시간과 속도를 점차 늘리세요</li>\n <li>가벼운 스트레칭과 가동성 운동은 괜찮습니다</li>\n <li>피하세요: 윗몸일으키기, 크런치, 플랭크, 무거운 것 들기, 충격이 큰 운동, 골반저에 아래쪽 압력을 높이는 모든 활동</li>\n <li>몸의 신호를 들으세요. 통증, 출혈 또는 골반 압박감이 늘어나면 속도를 늦추라는 뜻입니다</li>\n </ul>\n <h4>6주 검진 승인 후</h4>\n <p>임신 전에 하던 운동으로 점차 돌아갈 수 있습니다. 50% 강도로 시작해 몇 주에 걸쳐 천천히 늘리세요. 달리기, 고강도 인터벌 트레이닝(HIIT), 웨이트 운동 모두 재개할 수 있습니다. 하지만 가볍게 시작하세요.</p>\n <div class=\"callout rose\">\n <div class=\"callout-title\">복직근 이개</div>\n <p>복직근(\"식스팩\" 근육)의 양쪽이 벌어지는 것으로, 임신 후 매우 흔합니다. 일반적인 크런치와 윗몸일으키기는 악화시킬 수 있습니다. 골반저 물리치료사가 검사하고 안전하고 효과적인 운동을 알려줄 수 있습니다. 의사에게 소개를 요청하세요.</p>\n </div>\n <div class=\"callout\">\n <div class=\"callout-title\">골반저 물리치료</div>\n <p>분만 후 활용도가 낮지만 매우 효과적인 치료입니다. 요실금, 골반 장기 탈출증, 성관계 시 통증, 복직근 이개, 전반적인 골반저 근력 약화를 치료합니다. 6주 검진에서 소개를 요청하세요. 대부분의 보험에서 보장됩니다.</p>\n </div>"
    },
    "postpartum-danger": {
      "title": "산후 경고 신호와 추후 진료",
      "sub": "연락해야 할 때와 검진 일정",
      "body": "\n        <div class=\"callout alert\">\n          <div class=\"callout-title\">다음의 경우 응급실에 가거나 911에 전화하세요</div>\n          <p>흉통 또는 호흡 곤란 · 경련 · 전에 겪어본 적 없는 갑작스러운 심한 두통 · 뇌졸중 증상(얼굴 한쪽 처짐, 팔 힘 빠짐, 발음 어눌함) · 자신이나 아기를 해치고 싶은 생각</p>\n        </div>\n        <div class=\"callout rose\">\n          <div class=\"callout-title\">다음의 경우 산부인과 의사 / 조산사에게 연락하세요</div>\n          <p>열 &gt;100.4°F · 2시간 동안 한 시간에 생리대 1개 이상 적심 · 이부프로펜/타이레놀로도 낫지 않는 심한 두통 · 시야 변화 · 다리의 발적, 부기 또는 열감(DVT, 심부정맥혈전증) · 상처가 벌어지거나 발적이 번지거나 고름이 나옴 · 소변 보기 어려움 · PPD 또는 불안 증상</p>\n        </div>\n        <h4>산후 검진 일정</h4>\n        <table class=\"data-table\">\n          <tr><th class=\"rose\">시기</th><th class=\"rose\">목적</th></tr>\n          <tr><td><strong>1~3일</strong><br>(제왕절개 또는 합병증이 있는 경우)</td><td>상처 확인, 혈압, 통증 관리</td></tr>\n          <tr><td><strong>2주</strong><br>(현재 ACOG 권장)</td><td>기분 선별검사(에든버러 척도), 혈압, 절개 부위/회음부 확인, 모유 수유 지원</td></tr>\n          <tr><td><strong>6주</strong></td><td>전신 신체검사, 골반 검진, 피임, 성관계 및 운동 승인, 필요시 갑상선 검사</td></tr>\n        </table>\n        <div class=\"callout\">\n          <div class=\"callout-title\">6주 검진에서 물어볼 질문</div>\n          <p>피임 · 골반저 물리치료 소개 · 전면적인 운동 재개 · 복직근 이개 검사 · 성관계 문제와 건조함 · 기분 및 PPD 선별검사 · 절개 부위 또는 회음부 회복 · 그동안 쌓인 기타 질문</p>\n        </div>"
    },
    "breastfeeding": {
      "title": "모유 수유: 시작하기",
      "sub": "젖 물리기, 초유, 잘 되고 있는지 확인하는 방법",
      "body": "<p class=\"lead navy\">모유 수유는 자연스러운 일이지만 연습이 필요합니다. 대부분의 어려움은 좋은 도움을 받으면 해결할 수 있습니다. <strong>퇴원하기 전에 모유 수유 상담사를 만나 달라고 요청하세요. 여러분이 이용할 수 있는 가장 소중한 자원 중 하나입니다.</strong></p>\n <h4>생후 1–3일: 초유</h4>\n <p>처음 나오는 \"젖\"은 초유입니다. 걸쭉하고 황금빛 노란색이며, 양이 적습니다(온스가 아니라 티스푼 단위). 이것이 정상입니다. 초유에는 항체와 면역 물질이 가득하고, 신생아에게 꼭 필요한 것들이 들어 있습니다. 성숙유는 보통 생후 2–5일쯤 나오기 시작합니다(제왕절개 후에는 조금 더 늦어지는 경우가 많습니다).</p>\n <h4>젖 물리기. 가장 중요한 것</h4>\n <ul>\n <li>아기 입이 유두뿐 아니라 유륜 대부분을 덮어야 합니다</li>\n <li>아기의 두 입술이 바깥쪽으로 뒤집혀 있어야 합니다(안으로 말리면 안 됨)</li>\n <li>삼키는 소리, 부드러운 \"꿀꺽\" 소리, 가 들려야 하고, 딱딱거리는 소리가 나면 안 됩니다</li>\n <li>아기의 코와 턱이 모두 가슴에 닿아야 합니다</li>\n <li>제대로 물렸다면 처음 20–30초 이후에는 아프지 않아야 합니다. 계속 아프면 깨끗한 손가락으로 빨아들이는 힘을 풀고 다시 시도하세요.</li>\n </ul>\n <h4>수유 횟수</h4>\n <p>첫 몇 주 동안은 24시간에 8–12회. 아기가 원할 때마다 먹이세요. 시계를 보지 말고 배고픔 신호(입으로 찾는 반응, 손을 입으로 가져감, 빠는 동작, 칭얼거림)를 살피세요. 신생아는 그렇게 자주 먹어야 합니다. 젖이 부족하다는 뜻이 아닙니다.</p>\n <div class=\"callout navy\">\n <div class=\"callout-title\">아기가 충분히 먹고 있는지 확인하는 방법</div>\n <p><strong>기저귀:</strong> 생후 4–5일부터 하루에 젖은 기저귀 6장 이상, 노란색의 알갱이가 섞인 변 3–4회가 정상입니다. <strong>체중:</strong> 출생 시 체중은 생후 10–14일 안에 회복되어야 합니다. 생후 5일 이후에는 하루에 ½–1 oz 정도 늘어야 합니다. <strong>아기 상태:</strong> 수유 후 만족해하고, 깨어 있을 때 활기가 있습니다.</p>\n </div>"
    },
    "bf-challenges": {
      "title": "모유 수유 문제와 해결 방법",
      "sub": "유두 통증, 젖 몽우리, 젖양 걱정, 유방염",
      "body": "<table class=\"data-table\">\n <tr><th class=\"navy\">문제</th><th class=\"navy\">대처법</th></tr>\n <tr><td><strong>유두 통증</strong></td><td>먼저 젖 물리기 자세를 확인하세요. 가장 흔한 원인입니다. 수유 후 짜낸 모유나 라놀린을 바르세요. 공기 중에 말리세요. 보통 생후 5일 이후 젖이 제대로 나오고 물리는 자세가 좋아지면 나아집니다.</td></tr>\n <tr><td><strong>젖 몽우리(울혈)</strong></td><td>자주 수유하거나 유축하세요(2–3시간마다). 수유 전에 따뜻한 찜질을 하면 젖이 잘 나옵니다. 수유 후에는 차가운 찜질로 붓기를 줄이세요. 미열이 날 수 있습니다. &gt;100.4°F이면 의사에게 연락하세요.</td></tr>\n <tr><td><strong>젖양이 부족한 것 같을 때</strong></td><td>더 자주 먹이세요. 젖양은 수요를 따라갑니다. 젖 물리기 자세를 바로잡으세요. 수유 후 유축을 하면 더 만들라는 신호가 됩니다. 모유 수유 상담사를 만나세요. 부족하다고 느끼는 경우 대부분 실제로는 충분합니다.</td></tr>\n <tr><td><strong>유관 막힘</strong></td><td>가슴에 단단하고 아픈 덩어리가 생깁니다. 수유 중에 유두 쪽으로 마사지하세요. 수유 전에 따뜻한 찜질을 하세요. 그쪽 가슴을 자주 비우세요. 보통 1–2일 안에 좋아집니다.</td></tr>\n <tr><td><strong>유방염</strong></td><td>독감 같은 증상(열, 몸살, 피로)과 함께 가슴의 빨갛고 아픈 부위가 생깁니다. 모유 수유를 계속하세요. 멈추면 더 나빠집니다. 보통 항생제가 필요합니다. 의사에게 연락하세요.</td></tr>\n <tr><td><strong>유두 칸디다증(아구창)</strong></td><td>수유 중과 수유 후에 날카롭고 타는 듯한 통증이 있습니다. 유두가 분홍빛으로 반짝입니다. 엄마와 아기가 동시에 항진균제 치료를 받아야 합니다. 담당 의사와 아기의 소아과 의사에게 연락하세요.</td></tr>\n </table>\n <div class=\"callout navy\">\n <div class=\"callout-title\">유축</div>\n <p>전동 이중 유축기는 ACA(오바마케어)에 따라 대부분의 미국 보험에서 보장됩니다. 유축은 아기가 직접 빨 수 없을 때 젖양을 유지하게 하고, 다른 사람이 아기에게 먹일 수 있게 하며, 냉동 비축분을 만들 수 있게 합니다. 모유는 냉장 4일, 냉동 6–12개월 보관할 수 있습니다.</p>\n </div>\n <div class=\"callout\">\n <div class=\"callout-title\">분유를 보충하거나 분유로 먹여도 괜찮습니다</div>\n <p>도움을 받아도 모유 수유가 잘 안 된다면, 분유를 보충하는 것은 실패가 아니라 아기를 먹이는 일입니다. 잘 먹고 잘 자라는 아기가 가장 중요합니다. 많은 가족이 모유와 분유를 함께 먹이며 성공적으로 키우고 있습니다.</p>\n </div>"
    },
    "formula": {
      "title": "분유 수유",
      "sub": "분유 선택, 조유, 안전한 보관",
      "body": "<p class=\"lead navy\">분유는 아기에게 안전하고 완전한 영양 공급원입니다. 최선의 수유 방법은 아기에게 영양을 공급하고 가족 모두가 건강하게 지낼 수 있는 방법입니다.</p>\n <h4>분유 선택하기</h4>\n <ul>\n <li>일반적인 우유 기반 철분 강화 분유는 대부분의 건강한 만삭아에게 적합합니다</li>\n <li>두유 분유는 특정한 식이 또는 종교적 이유가 있을 때 적합합니다</li>\n <li>저알레르기(가수분해) 분유는 우유 단백질 알레르기가 확진된 아기를 위한 것입니다. 소아과 의사와 상의 없이 바꾸지 마세요</li>\n <li>흔한 칭얼거림을 해결하려고 분유 브랜드를 자주 바꾸지 마세요. 대부분 도움이 되지 않습니다</li>\n </ul>\n <h4>분유 조유하기</h4>\n <ul>\n <li>포장지의 설명을 정확히 따르세요. 분유와 물의 비율은 정밀하게 설계되어 있습니다</li>\n <li>안전한 식수 기준을 충족하는 물을 사용하세요. 생후 2개월 미만이거나 면역력이 약한 아기라면 수돗물을 끓여서 식혀 사용하세요</li>\n <li>데울 때는 젖병을 따뜻한 물이 담긴 그릇에 넣으세요. <strong>절대 전자레인지를 사용하지 마세요</strong>. 고르게 데워지지 않아 아기 입을 데게 할 수 있습니다</li>\n </ul>\n <h4>양과 횟수</h4>\n <ul>\n <li>신생아(0–1개월): 2–3시간마다 1–2 oz(하루 8–12회)</li>\n <li>생후 2개월: 3–4시간마다 3–4 oz</li>\n <li>생후 4개월: 4시간마다 4–6 oz</li>\n <li>아기가 원할 때 먹이세요. 이것은 지침이지 규칙이 아닙니다</li>\n </ul>\n <table class=\"data-table\">\n <tr><th class=\"navy\">보관</th><th class=\"navy\">기한</th></tr>\n <tr><td>먹기 시작한 젖병</td><td>1시간 안에 사용하거나 버리세요</td></tr>\n <tr><td>조유했지만 먹이지 않은 것(냉장)</td><td>최대 24시간</td></tr>\n <tr><td>타지 않은 분유 가루(밀봉, 실온)</td><td>포장지의 유통기한을 따르세요</td></tr>\n </table>\n <div class=\"callout alert\">\n <div class=\"callout-title\">절대 하지 마세요</div>\n <p>생후 12개월 전에 일반 우유 주기 · 젖병에 시리얼 넣기 · 오래 먹이려고 분유를 묽게 타기 · 지시보다 진하게 타기 · 유통기한 지난 분유 사용하기</p>\n </div>"
    },
    "cord-care": {
      "title": "제대 관리",
      "sub": "깨끗하고 건조하게 유지하기, 걱정해야 할 때",
      "body": "<p class=\"lead navy\">제대(탯줄) 끝부분은 1–3주 안에 저절로 말라서 떨어집니다. 여러분이 할 일은 깨끗하고 건조하게 유지하는 것입니다.</p>\n <h4>시간에 따른 정상적인 모습</h4>\n <ul>\n <li>출생 직후: 노란빛이 도는 초록색, 부드럽고 고무 같은 느낌</li>\n <li>생후 1–5일: 마르기 시작하며 갈색으로 변함</li>\n <li>생후 5–14일: 점점 쭈글쭈글해지고 검게 변함</li>\n <li>저절로 떨어집니다. 겨우 매달려 있는 것처럼 보여도 잡아당기지 마세요</li>\n </ul>\n <h4>관리 방법</h4>\n <ul>\n <li><strong>건조하게 유지:</strong> 끝부분이 떨어질 때까지는 스펀지 목욕만 하세요. 물에 담그면 안 됩니다</li>\n <li><strong>기저귀를 아래로 접어</strong> 끝부분이 공기에 노출되게 하고 소변이 닿지 않게 하세요</li>\n <li><strong>헐렁하고 통풍이 잘 되는 옷</strong>. 제대를 문지르는 바디슈트나 옷은 피하세요</li>\n <li><strong>알코올 솜은 필요 없습니다</strong>. 연구에 따르면 깨끗하고 건조한 관리만으로도 똑같이 또는 더 빨리 낫습니다. 병원에 고유한 지침이 있을 수 있으니 그 안내를 따르세요.</li>\n </ul>\n <h4>정상적인 소견</h4>\n <ul>\n <li>떨어질 때쯤 바닥 부분에 소량의 마른 피가 보임. 정상</li>\n <li>바닥 부분에 약간의 습기나 소량의 맑은 분비물. 보통 정상</li>\n <li>마르는 동안 약한 냄새. 일반적으로 정상</li>\n </ul>\n <div class=\"callout alert\">\n <div class=\"callout-title\">소아과 의사에게 연락해야 할 경우</div>\n <p><strong>주변 피부로 발적이 퍼지는 경우</strong>. 이것은 제대염(피부 감염)으로 신속한 치료가 필요합니다 · 고약하거나 심한 냄새 · 노란색 또는 초록색 고름 · 살짝 눌러도 멈추지 않는 출혈 · 특별한 이유 없이 5–6주가 지나도 떨어지지 않는 경우</p>\n </div>"
    },
    "normal-newborn": {
      "title": "정상적인 신생아의 모습과 행동",
      "sub": "걱정스러워 보이지만 전혀 정상인 것들",
      "body": "<p class=\"lead navy\">신생아의 정상적인 특징 중 많은 것이 초보 부모에게는 걱정스럽게 보입니다. 무엇을 예상해야 하는지 알려드립니다.</p>\n <table class=\"data-table\">\n <tr><th class=\"navy\">보이는 것</th><th class=\"navy\">정상인가요?</th></tr>\n <tr><td>뾰족하거나 눌린 모양의 머리</td><td>✓ 정상. 며칠 안에 없어집니다</td></tr>\n <tr><td>맥박이 뛰는 듯 보이는 천문(숨구멍)</td><td>✓ 정상. 정상입니다</td></tr>\n <tr><td>치즈 같은 하얀 피지(태지)</td><td>✓ 정상. 보호막이니 스며들게 두세요</td></tr>\n <tr><td>어깨/등의 가는 솜털(태모)</td><td>✓ 정상. 몇 주 안에 빠집니다</td></tr>\n <tr><td>노란 피부나 눈(황달)</td><td>흔함. 관찰이 필요합니다</td></tr>\n <tr><td>부은 가슴(여아 또는 남아)</td><td>✓ 정상. 엄마의 호르몬 때문</td></tr>\n <tr><td>부은 음순이나 음낭</td><td>✓ 정상. 엄마의 호르몬 때문</td></tr>\n <tr><td>여아: 피가 섞이거나 점액성 질 분비물</td><td>✓ 정상. 호르몬 이탈 현상</td></tr>\n <tr><td>가끔 눈이 몰림</td><td>✓ 정상. 생후 ~4개월까지 정상</td></tr>\n <tr><td>피부가 벗겨짐(생후 1–3일)</td><td>✓ 정상. 특히 예정일이 지난 아기에서 흔함</td></tr>\n <tr><td>자주 재채기</td><td>✓ 정상. 감기가 아닙니다</td></tr>\n <tr><td>끊임없는 딸꾹질</td><td>✓ 정상. 아주 정상입니다</td></tr>\n <tr><td>뾰루지 같은 발진(신생아 독성 홍반)</td><td>✓ 정상. 해롭지 않으며 며칠 안에 없어집니다</td></tr>\n <tr><td>짙은 색의 첫 변(태변)</td><td>✓ 정상. 24–48시간 안에 나와야 합니다</td></tr>\n </table>\n <div class=\"callout alert\">\n <div class=\"callout-title\">즉시 소아과 의사에게 연락해야 할 경우</div>\n <p>직장 체온 ≥ 100.4°F의 열(신생아에게는 심각합니다. 항상 직장 체온을 재세요) · 먹기를 거부함 · 심한 황달 · 숨쉴 때마다 끙끙거리는 소리 · 파란 입술 또는 매우 창백한 피부 · 달래도 그치지 않는 울음 · 생후 5일 이후 젖은 기저귀가 하루 6장 미만 · 목이 뻣뻣함</p>\n </div>"
    },
    "safe-sleep": {
      "title": "아기의 안전한 수면",
      "sub": "영아 돌연사 증후군(SIDS) 예방의 ABC",
      "body": "<p class=\"lead navy\">안전한 수면 습관은 SIDS(영아 돌연사 증후군)와 수면 관련 영아 사망을 예방합니다. 미국에서는 이로 인해 매년 약 3,500명의 아기가 사망합니다. 이 지침들은 생명을 구합니다.</p>\n <div class=\"callout navy\">\n <div class=\"callout-title\">안전한 수면의 ABC</div>\n <p><strong>A. Alone(혼자):</strong> 아기는 혼자 잡니다. 어른, 형제, 반려동물과 함께 자지 않습니다<br><strong>B. Back(바로 눕히기):</strong> 항상 아기를 바로 눕혀 재우세요. 잘 때마다, 돌보는 사람 누구든지<br><strong>C. Crib(아기 침대):</strong> 꼭 맞는 시트 하나만 있는 단단하고 평평한 수면 공간에서</p>\n </div>\n <h4>안전한 수면 환경</h4>\n <ul>\n <li>현재 CPSC(미국 소비자제품안전위원회) 안전 기준을 충족하는 아기 침대, 베이시넷 또는 플레이야드에 단단하고 평평한 매트리스</li>\n <li>수면 공간에는 <strong>다른 어떤 것도</strong> 넣지 않습니다. 베개, 담요, 범퍼 패드, 자세 교정 쿠션, 봉제 인형, 경사 쿠션 모두 안 됩니다</li>\n <li><strong>같은 방 사용</strong>(아기를 같은 방에서 자되 같은 침대는 아닌 곳에)를 생후 최소 6개월까지 하면 SIDS 위험이 최대 50%까지 줄어듭니다. 적극 권장됩니다</li>\n <li>수면 공간을 금연 상태로 유지하세요. 담배 연기에 노출되면 위험이 크게 높아집니다</li>\n <li><strong>잘 때 공갈 젖꼭지</strong>를 주면 SIDS 위험이 줄어듭니다. 모유 수유가 자리 잡은 후(약 생후 3–4주)부터 주세요</li>\n <li>아기가 시원하고 편안하게 유지하세요. 과열은 위험 요인입니다</li>\n </ul>\n <div class=\"callout gold\">\n <div class=\"callout-title\">터미 타임(깨어 있을 때 &amp; 지켜보는 경우에만)</div>\n <p>아기가 깨어 있고 지켜보는 동안의 터미 타임(엎드려 놀기)은 목과 어깨 발달과 머리 납작해짐 예방에 필수적입니다. 출생 때부터 하루 여러 번 2–3분씩 시작하세요. 생후 3개월까지 하루 총 30분으로 늘리세요.</p>\n </div>\n <p>잠든 아기를 흔들의자, 자동차 카시트(차 밖에서), 바운서, 경사형 수면용품에서 오래 자게 두지 마세요. 이것들은 안전한 수면 환경이 아닙니다.</p>"
    },
    "followup-appts": {
      "title": "아기와 산모를 위한 후속 진료 예약",
      "sub": "일정과 각 진료에서 하는 일",
      "body": "<p class=\"lead navy\">병원에서 퇴원하기 전에 아래 진료 예약이 잡혔는지 꼭 확인하세요. 예약 없이 퇴원하지 마세요.</p>\n <h4>아기 (소아과 의사)</h4>\n <table class=\"data-table\">\n <tr><th class=\"navy\">시기</th><th class=\"navy\">목적</th></tr>\n <tr><td><strong>생후 2–5일</strong></td><td>체중 확인. 출생 시 체중을 되찾고 있는지 확인하는 것이 매우 중요합니다. 황달 평가. 수유 상태 평가. 신생아 선별검사 후속 확인.</td></tr>\n <tr><td><strong>생후 2주</strong></td><td>체중이 출생 시 체중으로 돌아왔나요? 발달과 수유 상태 확인. 제대(배꼽) 끝부분 확인.</td></tr>\n <tr><td><strong>생후 2개월</strong></td><td>첫 예방접종, 성장과 발달 이정표 확인</td></tr>\n <tr><td><strong>생후 4, 6, 9, 12개월</strong></td><td>성장, 발달, 예방접종 (일정은 아동기 내내 계속됩니다)</td></tr>\n </table>\n <h4>산모님 (산부인과 의사/조산사)</h4>\n <table class=\"data-table\">\n <tr><th class=\"navy\">시기</th><th class=\"navy\">목적</th></tr>\n <tr><td><strong>1–3일 후</strong> (제왕절개 또는 합병증이 있는 경우)</td><td>상처 확인, 혈압 관리, 통증 관리</td></tr>\n <tr><td><strong>2주 후</strong></td><td>기분 상태 선별검사, 혈압, 상처/회음부 확인, 모유수유 지원</td></tr>\n <tr><td><strong>6주 후</strong></td><td>전신 신체검사, 골반 검사, 피임 상담, 운동 재개 허가</td></tr>\n </table>\n <div class=\"callout navy\">\n <div class=\"callout-title\">퇴원 전에 물어볼 질문들</div>\n <p>첫 진료 전에 궁금한 점이 생기면 누구에게 전화하면 되나요? · 아기가 잘 먹고 있나요. 그렇지 않다면 어떻게 알 수 있나요? · 어떤 경우에 소아과에 전화해야 하나요? · 후속 확인이 필요한 비정상 검사 결과가 있었나요? · 밤에 아기를 깨워서 먹여야 하나요? · 상처 관리 방법은 무엇인가요?</p>\n </div>"
    },
    "faq-deli": {
      "title": "델리 고기(슬라이스 햄)와 소프트 치즈를 먹어도 되나요?",
      "sub": "",
      "body": "<p>주된 위험은 <em>리스테리아(Listeria)</em>라는 세균 감염입니다. 드물지만 임신 중에는 심각할 수 있고 태반을 통과할 수 있습니다. FDA(미국 식품의약국)는 저온살균되지 않은 치즈와 델리 고기는 김이 날 정도(165°F)로 가열하지 않는 한 피하라고 권고합니다. 저온살균된 소프트 치즈 대부분(예: 저온살균 브리 치즈, 포장된 페타 치즈)은 안전합니다. 가끔 델리 고기를 먹는 것의 전반적인 위험은 매우 낮습니다. 이 지침은 예방 차원이며, 칠면조 샌드위치 하나로 반드시 병에 걸린다는 뜻은 아닙니다. 걱정될 때는 가열해서 드세요.</p>"
    },
    "faq-coffee": {
      "title": "카페인을 조금이라도 섭취해도 되나요?",
      "sub": "",
      "body": "<p>네. ACOG(미국 산부인과학회)는 카페인을 <strong>하루 200 mg 미만</strong>으로 제한할 것을 권합니다(드립 커피 12온스 한 잔 정도). 이 정도 수준에서는 임신에 해롭다는 근거가 확립되지 않았습니다. 차, 탄산음료, 초콜릿에도 카페인이 들어 있으니 모두 합산해서 계산하세요. 줄이는 것은 합리적이지만, 완전히 끊는 것은 개인의 선택이지 의학적으로 꼭 필요한 것은 아닙니다.</p>"
    },
    "faq-hair-dye": {
      "title": "임신 중에 머리 염색을 해도 되나요?",
      "sub": "",
      "body": "<p>네. 염색약은 두피를 통해 아주 소량만 흡수됩니다. 일반적인 미용실이나 가정 염색 수준의 양으로 태아에게 해롭다는 연구 결과는 발표된 바 없습니다. 대부분의 의사는 특히 임신 초기(첫 3개월) 이후에는 안전하다고 봅니다. 하이라이트(호일) 시술은 두피 접촉이 훨씬 적습니다. 걱정되신다면 주요 장기 발달이 끝나는 임신 중기까지 기다리셔도 됩니다.</p>"
    },
    "faq-exercise-mc": {
      "title": "운동이 유산을 일으키나요?",
      "sub": "",
      "body": "<p>아니요. 건강한 임신에서 적당한 운동은 유산을 일으키지 않습니다. 이것은 임신에 관한 가장 널리 퍼진 속설 중 하나입니다. 초기 유산은 거의 항상 배아의 염색체 이상이 원인이며, 운동, 성관계, 스트레스, 산모가 한 어떤 행동 때문이 아닙니다. 운동은 해롭기는커녕 오히려 몸을 보호합니다. 임신 전 관리 섹션의 운동 지침을 참고하세요.</p>"
    },
    "faq-sex-pregnancy": {
      "title": "임신 중 성관계는 안전한가요?",
      "sub": "",
      "body": "<p>네, 합병증이 없는 정상적인 임신에서는 안전합니다. 성관계는 유산이나 조산을 일으키지 않으며, 아기(양수로 보호되어 있습니다)에게 해를 끼치지도 않습니다. 의사는 다음과 같은 특정 상황에서만 골반 휴식(성관계 금지)을 권합니다: 전치태반, 조산 위험, 원인 불명의 질 출혈, 일부 자궁경부 질환, 또는 양수가 터진 후. 확실하지 않다면 다음 진료 때 물어보세요.</p>"
    },
    "faq-vaccines": {
      "title": "임신 중 백신을 맞아도 안전한가요?",
      "sub": "",
      "body": "<p>일부는 안전하고 일부는 그렇지 않습니다. 담당 의료진과 상의하세요.</p>"
    },
    "faq-eat-for-two": {
      "title": "두 사람 몫으로 먹어야 하나요?",
      "sub": "",
      "body": "<p>아니요. \"두 사람 몫으로 먹기\"는 잘못된 상식입니다. 임신 초기에는 추가로 필요한 칼로리가 아주 적습니다. 임신 후기가 되면 하루에 약 300칼로리만 더 드시면 됩니다(우유 한 잔과 바나나 하나 정도). 양보다 영양의 질이 훨씬 더 중요합니다. 단백질, 철분, 엽산, 칼슘, 오메가-3 지방산에 집중하세요. 임산부용 비타민이 부족한 부분을 채워 주지만, 균형 잡힌 식사를 대신할 수는 없습니다.</p>"
    },
    "faq-hot-tub": {
      "title": "목욕이나 온수 욕조를 이용해도 되나요?",
      "sub": "",
      "body": "<p>따뜻한 목욕은 임신 기간 내내 괜찮습니다. 다만 온수 욕조, 사우나, 찜질방처럼 몸의 중심 체온을 102°F (39°C) 이상으로 올리는 것은 권하지 않습니다. 특히 임신 초기에는 체온 상승이 신경관 결손과 관련이 있습니다. 온수 욕조를 꼭 이용하고 싶다면 뜨겁지 않은 편안한 온도로 맞추고, 10분 이내로 제한하고, 임신 초기에는 피하세요. 일반 가정의 물 온도(98–100°F)로 하는 따뜻한 목욕은 안전합니다.</p>"
    },
    "faq-epidural-csec": {
      "title": "경막외 마취를 하면 제왕절개 위험이 높아지나요?",
      "sub": "",
      "body": "<p>아니요. 이것은 산과학에서 가장 많이 연구된 질문 중 하나입니다. 여러 대규모 무작위 대조 연구와 메타 분석 결과, 경막외 마취는 제왕절개 비율을 높이지 <strong>않는다</strong>는 것이 확인되었습니다. 경막외 마취가 힘주기 단계를 약간 길어지게 할 수는 있지만, 여유를 갖고 간호사의 안내에 따르면 안전하게 진행됩니다. 경막외 마취는 활동기 진통 중이라면 언제든 요청할 수 있습니다. \"너무 이르다\"거나 \"너무 늦었다\"는 기준은 없습니다.</p>"
    },
    "faq-routine-episiotomy": {
      "title": "찢어지는 것을 막으려면 회음 절개를 해야 하나요?",
      "sub": "",
      "body": "<p>아니요. 일상적인 회음 절개(질 입구를 수술로 절개하는 것)는 더 이상 ACOG(미국 산부인과 학회)에서 권장하지 않습니다. 연구 결과는 일관되게 <strong>자연적으로 찢어진 상처가 대체로 더 잘 아물고</strong> 합병증(통증과 장기적인 골반저 문제 포함)도 더 적다는 것을 보여 줍니다. 자연분만을 하는 대부분의 산모님은 어느 정도 열상이 생기지만, 많은 경우 가벼운 정도(1도 열상)입니다. 아기가 태아 곤란으로 빨리 나와야 하는 경우처럼 특별한 의학적 이유가 있을 때는 여전히 회음 절개가 적절합니다.</p>"
    },
    "faq-water-breaking": {
      "title": "양수가 터지면 제왕절개를 해야 하나요?",
      "sub": "",
      "body": "<p>아니요. 만삭에 양막이 파열(양수가 터짐)되면 대부분의 산모님은 12시간 안에 자연스럽게 진통이 시작됩니다. 진통이 시작되지 않으면 감염 위험을 줄이기 위해 유도 분만을 권합니다. 지침상 18–24시간 안에 분만을 마치는 것입니다. GBS(B군 연쇄상구균) 양성이라면 즉시 항생제를 시작합니다. 다른 의학적 이유가 있을 때만 제왕절개가 필요합니다. 양수가 터졌다는 것만으로는 제왕절개 이유가 되지 않습니다.</p>"
    },
    "faq-eat-in-labor": {
      "title": "분만 중에 먹거나 마셔도 되나요?",
      "sub": "",
      "body": "<p>저위험 산모가 초기 진통 단계라면, 현재 ACOG(미국 산부인과학회) 지침은 가벼운 음식과 맑은 액체 섭취를 지지합니다. 하지만 경막외 마취(무통주사)를 맞았거나, 피토신(Pitocin, 진통 촉진제)을 투여 중이거나, 전신 마취가 필요할 위험이 높은 경우(제왕절개 가능성)에는 대부분의 병원에서 전신 마취 시 흡인(위 내용물이 폐로 넘어가는 것) 위험 때문에 얼음 조각이나 물 몇 모금만 허용합니다. 해당 병원의 구체적인 방침을 꼭 확인하세요. 곁에서 도와주는 분께: 간식을 챙겨 오세요. 분만은 긴 하루가 될 수 있습니다.</p>"
    },
    "faq-vbac": {
      "title": "전에 제왕절개를 했으면 이번에도 꼭 제왕절개를 해야 하나요?",
      "sub": "",
      "body": "<p>꼭 그렇지는 않습니다. 제왕절개 후 질식 분만(VBAC)은 이전에 자궁 아래쪽을 가로로 한 번 절개한 산모라면 많은 경우 안전하고 적절한 선택지입니다. 성공률은 60–80%입니다. 가능 여부에 영향을 주는 요인으로는 이전 제왕절개의 이유, 현재 임신 상태, 자궁 절개 부위의 형태, 그리고 병원이 응급 상황에 대처할 수 있는 능력 등이 있습니다. 관심이 있다면 산전 관리 초기에 의사와 미리 상의하세요.</p>"
    },
    "faq-bf-bc": {
      "title": "모유 수유 중에도 임신이 되나요?",
      "sub": "",
      "body": "<p>네, 됩니다. 완전 모유 수유가 배란을 어느 정도 억제하기는 하지만, <strong>믿을 수 있는 피임 방법은 아닙니다</strong>. 생리가 돌아오기 전에도 배란하고 임신할 수 있습니다. \"수유성 무월경 피임법\"은 매우 엄격한 조건(낮에는 4시간마다, 밤에는 6시간마다 완전 모유 수유, 보충 수유 없음, 생리가 돌아오지 않은 상태)이 충족되어야 하며, 그 조건에서도 효과가 약 98%에 불과합니다. 퇴원 전에 피임 방법을 꼭 상의하세요.</p>"
    },
    "faq-stress-milk": {
      "title": "스트레스를 받으면 모유가 마르나요?",
      "sub": "",
      "body": "<p>갑작스러운 스트레스는 사출 반사(젖이 나오는 반사)를 일시적으로 방해할 수 있지만, 장기적인 모유 생산에는 영향을 주지 않습니다. 모유의 양은 수요에 따라 결정됩니다. 아기가 더 자주, 더 효과적으로 젖을 빨거나 유축을 더 자주 할수록 몸은 더 많은 모유를 만듭니다. 사출에 도움이 되는 방법으로는 아기와의 피부 맞닿기(캥거루 케어), 몸을 따뜻하게 하기, 이완 기법, 그리고 유축할 때 아기 사진 보기 등이 있습니다.</p>"
    },
    "faq-bonding": {
      "title": "아기를 보자마자 바로 애착이 생겨야 하나요?",
      "sub": "",
      "body": "<p>아니요. 애착은 하나의 순간이 아니라 과정입니다. 많은 엄마가 출산 직후 깊은 사랑을 느끼지만, 어떤 엄마는 그런 마음이 생기기까지 며칠, 몇 주, 그 이상이 걸리기도 합니다. 둘 다 완전히 정상입니다. 육체적 피로, 힘든 분만, 예상치 못한 결과, 그리고 산후 우울증(PPD)은 모두 초기 애착에 영향을 줄 수 있습니다. 2주 이상 아기에게 단절감이나 무감각함이 느껴진다면 의사에게 꼭 말하세요. 치료 가능한 산후 우울증의 신호일 수 있습니다.</p>"
    },
    "faq-ibuprofen-bf": {
      "title": "모유 수유 중에 이부프로펜을 먹어도 되나요?",
      "sub": "",
      "body": "<p>네, 됩니다. 이부프로펜은 모유 수유 중 가장 안전한 일반의약품(OTC) 중 하나입니다. 모유로 넘어가는 양이 아주 적습니다. 아세트아미노펜(Tylenol, 타이레놀)도 안전합니다. 이 두 가지가 산후와 모유 수유 중에 우선 권장되는 진통제입니다. 고용량 아스피린은 권장되지 않습니다(의사가 처방한 저용량 아스피린은 별개의 문제이므로 의사와 상의하세요). 나프록센(Aleve)은 모유로 더 많이 넘어가서 일반적으로 권장되지 않습니다. 본인의 구체적인 상황에 맞는지는 항상 진료팀과 확인하세요.</p>"
    },
    "faq-jaundice": {
      "title": "아기가 노랗게 보여요. 언제 심각한가요?",
      "sub": "",
      "body": "<p>신생아 황달(고빌리루빈혈증)은 생후 첫 주에 만삭아의 약 60%에게 나타납니다. 태아 적혈구가 정상적으로 분해되면서 생기는 것으로, 간이 아직 따라가는 중일 뿐입니다. 대부분은 가볍고 치료 없이 저절로 좋아집니다. 빌리루빈 수치가 매우 높을 때(극심한 경우 뇌 손상 위험), 아기가 너무 잠만 자거나 먹지 않을 때, 또는 생후 24시간 이내에 황달이 나타날 때가 걱정되는 경우입니다. 병원에서는 퇴원 전과 생후 2–5일 소아과 방문 시 빌리루빈을 검사합니다. 필요하면 광선 요법(빌리 라이트) 치료가 매우 효과적입니다.</p>"
    },
    "faq-newborn-procedures": {
      "title": "신생아 처치를 모두 꼭 받아야 하나요?",
      "sub": "",
      "body": "<p>일반적인 신생아 처치에는 다음이 포함됩니다: <strong>비타민 K 주사</strong>(치명적인 뇌출혈 위험을 낮춤), <strong>에리스로마이신 안연고</strong>(임질을 포함한 눈 감염을 줄임), <strong>B형 간염 백신 1차 접종</strong>, 그리고 <strong>신생아 대사 선별 채혈</strong>(발뒤꿈치 채혈로 PKU, 갑상선기능저하증, 겸상적혈구병 등 약 30가지 질환 검사). 모두 권장되는 이유는 조기에 개입하지 않을 때의 위험이 처치 자체의 위험보다 크기 때문입니다. 대부분의 주에서 법적으로 거부하실 수 있습니다. 먼저 담당 의료진과 위험에 대해 상의하시기를 권합니다.</p>"
    },
    "faq-first-bath": {
      "title": "아기의 첫 목욕은 언제 시켜야 하나요?",
      "sub": "",
      "body": "<p>WHO와 AAP(미국소아과학회)는 현재 첫 목욕을 출생 후 최소 24시간(이상적으로는 48시간) 늦추라고 권장합니다. 하얀 태지(버닉스 카세오사)에는 항균 성분이 있고 피부 보습에도 도움이 됩니다. 목욕을 늦추면 체온 유지와 혈당 안정에도 도움이 되고, 모유 수유 시작이 더 잘 되는 것과도 관련이 있습니다. 기다리는 것은 단순한 취향이 아니라 현재의 모범 사례입니다.</p>"
    }
  }
};
